### ISSUE TITLE
Prior information for fixed effects 

### ISSUE THREAD

**Issue by GenChangHSU** [brianstock/MixSIAR#130]
Hello Brian,
My name is Gen Chang, now a college student. I've been recently working with estimating dietary proportions of arthropod predators in rice fields. The arthropod samples were taken from three different crop stages and "stage" is treated as a fixed factor in the mixing model. On the other hand, I also got some source abundance data and I would like to incorporate this into the model. But the model returned an error saying that prior information cannot be set for fixed effect models. How can I deal with this problem? Do I really have to modify the function in order to set a prior for each stage level? 

Thanks a lot!

Gen Chang

**Comment by brianstock** [comment]
Hi Gen,

Sorry, I have not written a way to include priors for fixed effect models (on the `p.fac1` terms). See https://github.com/brianstock/MixSIAR/issues/79. If you do decide to go this route, please share.

-Brian

**Comment by GenChangHSU** [comment]
Hi Brian,

Thanks for the reply! That's all right! Perhaps one compromising way to solve the problem is to fit separate models for each level and set different priors, as you suggested in #79. On the other hand, I am willing to modify the code, but this might not be an easy task for me, considering my programming skills and background knowledge in Bayesian statistics. I think I would still take the above way as an expedient. Yet I may want to try it in the future though!

Thanks again!


Gen Chang

**Comment by brianstock** [comment]
Hi, an updated thought... I'm not sure this is possible with the way MixSIAR is structured. We can set an informative Dirichlet prior on the global p's easily because they are in proportion-space. However, these p's are then transformed to ILR-space, and the fixed/random effects are additive offsets in ILR-space, and the combined ILRs are back transformed to p's later. I don't know how you'd set an appropriate informative prior in ILR space.
