### ISSUE TITLE
Sample code output doesn't match manual's output

### ISSUE THREAD

**Issue by bkhobart** [brianstock/MixSIAR#147]
Hi Brian,

I have a question that may have a simple answer but has me completely stumped:

I am in the early stages of going through the working examples provided as vignettes and in the MixSIAR manual. I’m using the R script interface, not the GUI. When working with the BC wolves example, I have run into some apparent discrepancies in the results listed in the manual and those I get. For example, the screenshot of the G-R diagnostic output in the manual indicates that there are 41 variables, but when I ran the example (both re-typing code provided in vignette and running the complete sample code provided in package folder) I get 129 variables (same for Geweke). The region and pack SDs I received are also not the same as those listed in the manual. My mixing space plot is identical to the one in the manual, so I am quite certain the issue is not occurring in the data input stages.

Any feedback would be greatly appreciated!

Cheers, Brendan

**Comment by bkhobart** [comment]
Update: same result using GUI for wolves working example. I should clarify that I am not particularly concerned with this example, but rather ensuring that I am using MixSIAR _completely_ correctly before moving on to my own data.

**Comment by brianstock** [comment]
Hi Brendan,

Good catch! Sorry for the confusion... I've updated the code many times since putting those screenshots in the manual. The same model is being run, but the number of parameters I've asked JAGS to save is greater now.

Manual shows 41, which are just the parameters of interest:
- 24 pack-level diet proportions (8 packs x 3 sources)
- 9 region-level diet proportions (3 regions x 3 sources)
- 3 global-level diet proportions (3 sources)
- pack SD (variability of packs within region)
- region SD (variability of regions within overall)
- 2 epsilon terms (multiplicative error)
- deviance

24 + 9 + 3 + 1 + 1 + 2 + 1 = 41

In addition to these 41, I now also return the following from JAGS:
- 6 ilr.fac1 (3 regions x 2 sources)
- 16 ilr.fac2 (8 packs x 2 sources)
- 66 log-likelihoods (1 per mix datapoint)

41 + 6 + 16 + 66 = 129

Returning the ILR terms was necessary to make the continuous variable plots ([MixSIAR paper figures 5](https://peerj.com/articles/5096/#fig-5) and [6](https://peerj.com/articles/5096/#fig-6)). Returning the log-likelihoods was necessary to calculate LOO/WAIC ([MixSIAR paper table 1](https://peerj.com/articles/5096/#table-1)).

You can get the names of all parameters returned by JAGS with:
```
colnames(jags.1$BUGSoutput$sims.matrix)
```

**Comment by bkhobart** [comment]
Got it, makes sense! Many thanks for clarifying, and for putting in so much hard work on this package. I'm just transitioning to MixSIAR from SIAR, and am really impressed with its functionality and adaptability.

Cheers, Brendan
