### ISSUE TITLE
Discrimination data for surface water application

### ISSUE THREAD

**Issue by zfguo1** [brianstock/MixSIAR#148]
Hi everyone,
Based on the δ15N and δ18O values of surface water, I want to evaluate the conribution of pollution source . In this case, what values do the meand15N, SDd15N, meand18O, and  SDd18O in discrimnation data  represent, and how can I  caculate them?

**Comment by brianstock** [comment]
MixSIAR was originally motivated by mixing questions in the field of ecology - diet, movement, etc., where mixture data points are tissue samples from individual animals. Environmental scientists have also applied Bayesian mixing models to the question of sediment/water/pollution sourcing. "Discrimination" = a systematic difference in tracer (e.g. d13C, d15N) values that occurs between when/where you sample the sources and mixture. For example in ecology, we know that if a predator eats 100% prey tissue with d15N = 10, the predator tissue generally incorporates 14N at a higher rate than 15N, leading to an increase in the d15N in the predator tissue (say d15N = 13). Ecologists measure these discrimination values and shift the prey tracer values by these amounts.

In most soil/sediment/water applications I've seen, scientists set discrimination = 0 because they think that there is no process that modifies the d13C values as the material is transported from source to mixture. If there is, then you'd need to measure how much this happens before running a mixing model. If not, you simply need to create a discrimination.csv file with the right format (see examples) and all 0s.

**Comment by zfguo1** [comment]
Dear professor Stock,
Many thanks for your respones. I see what you mean.
Thanks again.
best,
Zhaofeng
