### ISSUE TITLE
Can SIAR  calculte  the contribution of  primary carbon souce to carnivorous fish

### ISSUE THREAD

**Issue by ZhongxinWU** [brianstock/MixSIAR#16]
Dear All
 In my current case , several categories of organic sources exist in the studied ecosystem. i want to identify which sort of organic matter mainly flow to the end of food web by the dominant fish,  i am questioning that whether i can use SIAR to calculate the percentage contribution of organic matters( seagrass，benthic  macroalgae， phytoplankton，benthicmicroalgae， epiphyte ) to carnivorous fish by stable isotopic values.  Meanwhile  the stomach contents analysis for the dominant fishes was conducted,  only the segments of  seagrass and macroalgae  were identified as the potential food items with exception of polychatea , amphipoda  and shrimp. it seems no significant to input all potential organic matter to SIAR . should  i just only  input  the isotopic signatures of segrass or macroalgae as the potential carbon sources to calculate the percentage contribution of  potential food items determined from stomach contents analysis or literature to the consumers

**Comment by eric-ward** [comment]
This is a good question - and more of a ecological rather than statistical one, so I don't know that there's a right answer.  

One option would be to analyze the stomach content data alone (this is simple with 2 sources -- you don't need MixSIAR), and the isotope data alone with MixSIAR. Finally, do a third analysis and construct a prior based on the 5 sources from the stomach content data (3 of those will have n = 0).

**Comment by ZhongxinWU** [comment]
Thanks Eric, what is prior analysis .

**Comment by eric-ward** [comment]
See the original MixSIR paper by Moore & Semmens (2008). That illustrates one option to include gut content data in SI analyses.
