### ISSUE TITLE
Not reaching convergence with informative priors

### ISSUE THREAD

**Issue by graceyee** [brianstock/MixSIAR#166]
Hi all,
I've been looking at the diet of two rat species using a moderately-informative prior based on stomach contents (with only invertebrates and plants being found) but whenever I use this informative prior my models never reach convergence when looking at the Geweke-Rubin diagnostics (going up to the "extreme" run time). So it seems like my priors are forcing my model into a solution that doesn't fit well with my isotope data. I tried reducing my number of sources from six to five and then down to four by grouping them together but that didn't help. When I use an "uninformative" prior then my models do reach convergence but the results do not seem very accurate (fungi comes out as the main food source) so I think it would be important to include priors. I'm a bit stumped at what to do next to improve convergence so would appreciate any help.

Here's a biplot of my data and sources for two different tissues for reference:
<img width="1059" alt="Screen Shot 2019-03-10 at 9 41 46 AM" src="https://user-images.githubusercontent.com/48351371/54083232-e8788780-4318-11e9-8925-57749f451dd9.png">

**Comment by nlaroche129** [comment]
Hello @graceyee, I have a very similar issue. I am curious what you did - as there are no replies here and this was 9 months ago. Thanks!

**Comment by graceyee** [comment]
Hi @nlaroche129, I did post elsewhere and got some replies there https://github.com/brianstock/MixSIAR/issues/91. Hope that helps you too. Unfortunately, I still haven't managed to fix my issue (have had a lot of work commitments so haven't been able to work on it thoroughly), but if you manage to get further with yours I would appreciate hearing how you did it if you wouldn't mind. I will let you know if I manage to make any substantial progress though.

**Comment by AndrewLJackson** [comment]
its impossible to give a definitive answer to this. Certainly one would need more information to even start to offer possible explanations, beyond the one you have come to yourself: i.e. that your informative prior and the data are giving very conflicting information. For one you have a large spread in the mixture data for both kiore and ship rat, spanning almost the full nitrogen range (at least if one ignores taiko source). Certainly for figure b, you have lots of mixture data points for both groups well below the mixing polygon formed by parea and plants at the lower nitrogen ends... this would mean the data would very much like fungi to be in the diet in order to explain those points, and balance that probably with some Weka.

In other more general terms, your mixing space and location of the mixtures will not be conducive to definitive separation of sources. You have lots of sources that form a straight line, and your mixture sits on that line, and so the model will struggle to tease them apart. e.g. in figure b you have fungi-parea-weka all in a line, and then plants-inverts-para also in a line with the mixtures sitting right on the same two lines. Then in figure a, you have plants-inverts-taiko in a line with the centre of the mixtures as well. the posteriors of these sources are alll likely to be highly correlated with each other - see the pairs matrix plot from the output.

one way to help this would be to include additional covariates, linear or fixed or random, to help to reduce the large variation in the mixture data. Essentially this would differentiate the expected values for similar rats and provide better fits. As far as I can guess, the model is bouncing all over the place around the centre of the mixing polygon in an attempt to explain the large variation. You would need to look at, and or provide here, figures for the fitted models including source proportion histograms and matrix correlations.

Ultimately, if you have strong belief in the diet of the animals and this is in conflict with what the SIA is telling you, then assumptions in one or both are incorrect. There is no fix to such conflict, but its possible that bulk SIA is not going to be all that helpful in this situation. You might need to consider compound specific SIA and/or fatty acid analysis to separate better plants, inverts, fungi and parea which I would guess would have rather distinct signatures.
