### ISSUE TITLE
“Individual” as a random effect

### ISSUE THREAD

**Issue by bdtaras** [brianstock/MixSIAR#167]
Early versions of the MixSIAR manuals (e.g., v1) included example models with “individual” as a random effect.  Later versions of the manual no longer include “individual” as a random effect in these same examples (e.g., wolves, lake, etc).  Why have examples with “individual” as a random effect been removed?  It is my understanding that using “individual” as a random effect is appropriate as long as the process only error structure is used (i.e., due to confounding with the residual error term).  Is my understanding correct?

**Comment by brianstock** [comment]
You're right, we removed the 'individual as RE' option. A couple reasons:

1. It's superfluous, since it's simple to add an "Individual" column in the mix data file and include that as a random (or fixed) effect.
2. Thought there could be confusion in what an "individual" is... the initial individual as RE option assumed individual mix data points were consumers, and you had one data point per consumer. But if you have multiple data points from the same consumer, this would be confusing. We thought best to just have the user specify what they mean in the mix data file.
3. Thought it was confusing with the different error term options, since like you say (correctly), adding the residual error term is a different way of allowing deviations of individual datapoints. Residual error: consumers' *isotope values* randomly deviate from the group mean/expectation (and all consumers' diet proportions are the same). Individuals as RE: consumers' *diet proportions* randomly deviate from group diet proportion, with a variance term calculated as a weighted sum of the source variance (no additional parameter fit).
