### ISSUE TITLE
Does MixSIAR run models differently than a year ago?

### ISSUE THREAD

**Issue by kelsey38** [brianstock/MixSIAR#168]
I used MixSIAR to run a series of mixing models a year ago for some data I was working on. Recently I had an update to some of the data so I had to run a couple of the models again. However, I noticed that the diagnostic output is different now than it used to be despite my having taken exactly the same steps. 

In this case, I'm running a model with 2 tracers (C13 and C14), and a fixed effect ("watershed" - samples were grouped by 3 separate watersheds). The old diagnostics had Gweke and Gelman diagnostics for 19 variables (4 sources by 3 watersheds = 12 p.fac1, plus 4 p.global for the 4 sources, plus resid.prop 1 and 2 = 19 total). 
The new diagnostics have Gweke and Gelman diagnostics for 39 variables. This includes the 19 mentioned above plus the following:

loglik[1-11]: 11 "loglik" variables, one for each of the consumers I assume 
ilr.fac1[x,y]: 9 of these, where x and y range from 1-3.

What are these additional diagnostics? Is the model running any differently than a year ago? Would that impact my data in such a way that I couldn't use what I ran a year ago alongside what I'm running now?

Below I am attaching a copy of the new diagnostic file:
[diagnostics.txt](https://github.com/brianstock/MixSIAR/files/3044745/diagnostics.txt)

And the old one:
[diagnostics.txt](https://github.com/brianstock/MixSIAR/files/3044746/diagnostics.txt)

Thanks!

**Comment by brianstock** [comment]
Hi Kelsey,

Nothing major about the model has changed in the last year. The change you're seeing in the diagnostic summary file is that I'm simply reporting more derived variables (the loglik and ilr.fac1 you mentioned). The underlying model and number of estimated parameters has not changed. The `ilr.fac1` variables were always there, just hidden from the user. They are converted from ILR to proportion space, and those `p.fac1` and `p.global` variables are the main interest. The `loglik` variables are the log-likelihood of each mix data point, which I added in order to calculate LOO and WAIC.

What is concerning is that your old model was converged, and your new one is not (Gelman-Rubin > 1.05 for half, and > 1.1 for several). Are you running the same chain length? How much has the data changed? You've only got 3-4 mix data points per watershed, so the result may be somewhat sensitive with that low sample size. I would look at the isospace plots for each watershed and confirm the data match the mixing model assumptions, there isn't any confounding of sources, etc. that would cause the model to not converge.

FYI all the code changes are documented in a few places:

- [Commit history](https://github.com/brianstock/MixSIAR/commits/master) (all very minor changes on Github)
- NEWS file [on CRAN](https://cran.r-project.org/web/packages/MixSIAR/news.html) or [on Github](https://github.com/brianstock/MixSIAR/blob/master/NEWS.md)
- [Folder of .R files](https://github.com/brianstock/MixSIAR/tree/master/R) on Github displays when each file was last changed

Hope that helps!

**Comment by kelsey38** [comment]
Hi Brian,

Thank you so much! That makes a lot of sense. The example I sent was just a test run, so the model should hopefully converge when I run it longer.

Thanks,

Scott
