### ISSUE TITLE
Error with model_compare

### ISSUE THREAD

**Issue by Melirax** [brianstock/MixSIAR#169]
Hi, 

I am trying to compare several models. They are all based on the same mix, source and discrim. They differ by the covariate that I add in the model.
When I run
`mod_comp <- compare_models(list(jags_0, jags_1), loo=TRUE)`

I systematically get (whatever model I compare):
`Error in data.frame(Model = mod.names, LOOic = LOOic, se_LOOic = se_LOOic,  : 
  arguments imply differing number of rows: 0, 2`

Any idea on how to fix this ?

Thanks

**Comment by brianstock** [comment]
Hmm, I haven't seen this before. It looks like you're getting all the way to line 141 where the results are bundled into a data frame for printing. I have several error checks in `compare_models`, but you're passing them. I'd like to add an additional check that will catch whatever is the problem here.

Have you tried going through `compare_models` line by line? That's what I'd have to do. You can either try this yourself and report back, or email me an R workspace with the saved `jags_0` and `jags_1` objects and I can play with it.

**Comment by Melirax** [comment]
I've emailed you the R workspace.

**Comment by Melirax** [comment]
Ok, so I've made more tests. It seems that the models must have names in the list.
So a ... 
```
jag.mods <-list(jags_0, jags_1)
names(jag.mods)<- c("Null", "Flood")
mod_comp <- compare_models(jag.mods, loo = TRUE)
```
... works fine!

**Comment by brianstock** [comment]
Hmm, I'm glad you got it to work but am surprised that was the issue... Line 96 of `compare_models` was supposed to catch that:
```
mod.names <- if(is.null(names(x))) paste0('model.',1:length(x)) else names(x)
```

I'll take a look at the R workspace you sent and come up with a fix so this doesn't happen again.
