### ISSUE TITLE
Different TDF factors for 2 types of consumer

### ISSUE THREAD

**Issue by EllenMcKee** [brianstock/MixSIAR#176]
Hi Brian,

Is it possible to include 2 different TDF factors - one each for the 2 consumers I am including in my model?

Thanks!

**Comment by AndrewLJackson** [comment]
I think no is the short answer. You could run the model twice.

The longer workaround is you could specify different sources for each of the two consumer groups and add the different TDFs on to each (taking care to add the variances and not the standard deviations, but converting back to sd for input) and also then setting TDFs = 0. Doing so is the same as what happens internally

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/





On 2 Jul 2019, at 14:02, EllenMcKee <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Brian,

Is it possible to include 2 different TDF factors - one each for the 2 consumers I am including in my model?

Thanks!

**Comment by EllenMcKee** [comment]
Great thank you! Is it also possible to load different TDF values for Nitrogen and Carbon?

**Comment by AndrewLJackson** [comment]
100% either as input or by adding to the sources.



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 2 Jul 2019, at 15:05, EllenMcKee <notifications@github.com<mailto:notifications@github.com>> wrote:


Great thank you! Is it also possible to load different TDF values for Nitrogen and Carbon?

**Comment by brianstock** [comment]
Thanks Andrew for replying - that's exactly what I was going to suggest. 

The difference between the two options is that if you fit both species in the same model using Species as a fixed effect, you only estimate one mixture covariance matrix. If you go the simpler route of running separate models for each Species, you end up estimating two mixture covariance matrices. Since your mix data have roughly the same variance and correlation, this means you're estimating more (unnecessary) parameters. Because of this, I'd recommend the workaround.

Like Andrew said, take care to add the variances and convert back to SD (i.e. take the square root of the sum of the variances), then use TDF = 0.
