### ISSUE TITLE
Adapting MCMC run options

### ISSUE THREAD

**Issue by MaartenWynants** [brianstock/MixSIAR#178]
Hi,

Due to a relative high number of sources (6), tracers (19) and high mix variability, the model did not converge using the extreme lenght. I was trying to manually adapt the MCMC variables:

run<-list(chainLength=6000000, burn=5000000, thin=500, chains=3, calcDIC=TRUE)
jags.1 <- run_model(run,mix,source,discr,model_filename, alpha.prior = alpha,process_err,resid_err)

However, after running for about 3/4 of the run, I get the following error 
'Initializing model

  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
  |************************                          |  48%
Error in update.jags(model, n.iter, ...) : Error in node X_iso[1,1]
Failure to calculate log density'

Any idea what this might be related to? Or is it not possible to manually adapt the MCMC parameters?

Regards,
Maarten

**Comment by brianstock** [comment]
Hmm, I'm sorry, that would be frustrating after such a long run. I haven't seen an error like that in the middle of a model run - JAGS has always either failed to initialize or worked for me. Have you made any progress on this?

Sounds like the issue reported [here](https://sourceforge.net/p/mcmc-jags/discussion/610037/thread/283c0730/):
"This error occurs when the function that calculates the log density returns NaN (not a number). If the error is only occurring in long runs then it suggests that the Markov chain is moving into a part of the parameter space where the density cannot be evaluated. You should look to the prior distributions to stop this from happening. Instead of using reference priors, try putting strong biologically plausible priors on your parameters. For example, you might want to put a much tighter prior on tauU to stop U[i] from getting too large.... "

**Comment by MaartenWynants** [comment]
Hi Brian,

Yes, I tried it another time (this time with an informative prior) and with increasing the burn to 54000000 (instead of 5000000) and it worked. I guess it was the model telling me that it would never  going to converge... 

Cheers,
Maarten
