### ISSUE TITLE
Presentation of summary statistics

### ISSUE THREAD

**Issue by DEHewitt** [brianstock/MixSIAR#181]
Hi all,

I have recently received reviewer comments for a paper looking at prawn diet. I have presented the mean (+/- SD) of source contributions, however one reviewer asked why we have opted for this instead of mode (and credible interval) which is more common when using a Bayesian approach. Other output to be included are the posterior density distributions and box-and-whisker plots.

I have attempted to calculate the mode (with some difficulty... I'm new to R) and would appreciate some tips on the following:
1. Why the mean (+/- SD) is/isn't appropriate
2. What else would be appropriate
3. An example of how to calculate the mode if this is the most appropriate summary statistic

Many thanks,

Dan

**Comment by brianstock** [comment]
Hi Dan,

This isn't necessarily specific to MixSIAR - it's a general "problem" when you try to summarize a (skewed) distribution with a point estimate. See these: [[1](https://stats.stackexchange.com/questions/298650/mean-median-or-mode-of-skewed-posterior)], Sec 8.4 in [[2](http://homepage.ntu.edu.tw/~ntucbsc/%A5%CD%AA%AB%C2%E5%BE%C7%B2%CE%ADp%BF%D4%B8%DF%A4@971008/[3]%20Chapter%208.pdf)], [[3](https://stats.stackexchange.com/questions/96371/should-the-mean-be-used-when-data-are-skewed)]. There are cases to be made for using the posterior mean, median or mode.
  - Mean: min expected squared error, influenced by tails
  - Median: min expected absolute error, less influenced by tails
  - Mode: akin to MLE.

If the distribution is nicely normal, mean = median = mode, and it doesn't matter. However, there are a couple special considerations because MixSIAR estimates *proportions* (that must sum to 1). They are almost always skewed. In addition, they can be multimodal... so I wouldn't pick the mode because it's not sensitive to multimodality. FWIW, Gelman likes the posterior median [[4](https://statmodeling.stat.columbia.edu/2016/05/14/point-summary-of-posterior-simulations/)]... *"if it’s one parameter at a time"*. Key here is that proportions are correlated, however.

For proportions, nice thing about the mean is that `sum(mean(p)) = 1`. This is not true for medians, and *definitely* not for modes. In the reasonable example below, the sum of the modes is only 0.48! Also see the function that calculates mode given a vector of draws from a distribution.

```
set.seed(123)
n.src = 3
alpha = c(1.4, 0.4, 1.2)
true.p = alpha/n.src
p = MCMCpack::rdirichlet(10000, alpha)

p.mean <- apply(p, 2, mean)
p.median <- apply(p, 2, median)
p.mode <- sapply(1:3, function(i) {ind = which(density(p[,i])$y == max(density(p[,i])$y)); density(p[,i])$x[ind]})

par(mfrow=c(1,n.src))
for(i in 1:n.src){
	hist(p[,i], breaks=50, col='grey', main=paste0("Source ",i))
	abline(v=p.mean[i], lty=1, lwd=3, col='red')
	abline(v=p.median[i], lty=2, lwd=3, col='red')
	abline(v=p.mode[i], lty=3, lwd=3, col='red')
}

sum(p.mean)
sum(p.median)
sum(p.mode)
```

**Comment by brianstock** [comment]
Ah, sorry, one more thing: definitely show the posterior density plots because point estimates of the source proportion posteriors may unsatisfactorily summarize the posteriors. That's because they can often be skewed, and sometimes are multimodal.

**Comment by ChrisHarrod** [comment]
This is an important discussion - one to include in courses and online guides and help files.

**Comment by DEHewitt** [comment]
Hi Brian,

Thank you for taking the time to give such a comprehensive response - this has been very helpful to me in answering the concerns of the reviewers, and widening my understanding.
