### ISSUE TITLE
Remove legend or chose aes in isospace plot

### ISSUE THREAD

**Issue by VirginiaMorera** [brianstock/MixSIAR#186]
Hi, 

When running a model with different factors, one of them with many levels, there is risk of the isospace plot ending up something like this: 
![imagen](https://user-images.githubusercontent.com/11058769/66744171-07756400-ee7c-11e9-82fb-3e205a350396.png)

where the legend completely covers the plot, and is scarcely informative anyway. Is it possible to add an option to avoid plotting the legend, or to select which factors are included in the aesthetics? In this case, I'd be happy to have only aes(color = YEAR) and forget about Ind altogether. 

The only way I've found to solve this so far is to generate another `mix` object without the ind information and use it only for plotting. 

Thanks!

**Comment by brianstock** [comment]
Hi Virginia,

Sorry, no there isn't a nice easy way to do this currently. Ideally I (or anyone!) would modify the plot function to accept a `plot.opts` list that gets passed to the `ggplot` call. Alternatively, I think there's a way to pass on additional options to a function call within a function using `...`. I didn't worry about it too much because I figured anyone creating figures for publication would need to modify the code anyway. So... the options are:

1. The workaround you mention, use a different `mix` object without `ind` for plotting only.
2. Fork the repository and modify your own version of the plotting function(s) directly.
3. Copy the relevant plot code into your working script and modify there (probably easier than 2).

**Comment by AndrewLJackson** [comment]
Some code here for a basic ggplot of isotope data https://github.com/andrewcparnell/simms_course/blob/master/aj-content/practicals/day-1-pm1/first-biplot.Rmd


--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/





On 15 Oct 2019, at 14:22, Brian Stock <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Virginia,

Sorry, no there isn't a nice easy way to do this currently. Ideally I (or anyone!) would modify the plot function to accept a plot.opts list that gets passed to the ggplot call. Alternatively, I think there's a way to pass on additional options to a function call within a function using .... I didn't worry about it too much because I figured anyone creating figures for publication would need to modify the code anyway. So... the options are:

  1.  The workaround you mention, use a different mix object without ind for plotting only.
  2.  Fork the repository and modify your own version of the plotting function(s) directly.
  3.  Copy the relevant plot code into your working script and modify there (probably easier than 2).
