### ISSUE TITLE
Possibility of using NON-parametric summary statistics as input data?

### ISSUE THREAD

**Issue by chbrax** [brianstock/MixSIAR#189]
Hi Brian,

MixSIAR offers the option to use summary data as input data. This must be in provided as mean and the standard deviation (SD). However, my data is not-normally distributed. Hence non-parametric statistics must be applied. This means that summary statistics can only be provided as median. As a measure of dispersion, I use the Median Absolute Deviation (MAD). The MAD is commonly referred to be a non-parametric analogue to the standard deviation. Hence it is also often used in the same way as the standard deviation. In publications, summary statistics are therefore shown as “median+/-MAD”.

My question in this regard is: Can the median and the MAD be used as summary statistic input data for MixSIAR instead of the mean and the SD?

From my experience, a considerable share of ecological data is not-normally distributed. However, many researchers still seem to use parametric tests (using mean+/-sd) instead of non-parametric tests (using median and indicating the 25th and 75th percentile, IQR, MAD,…). I assume this may also be the case for isotope data in food webs. As I have learnt, MixSIAR can summarize output data as median and 95% CI. I therefore hope that MixSIAR may also provide a solution for non-parametric input data. 

Thanks very much for your reply!

Cheers,
Chris

**Comment by AndrewLJackson** [comment]
hi chris

It can’t is the short of it. Non-parametric summaries are by definition not distributions, or at least are distortions without specified parameters. Within MixSIAR is a bayesian model that makes estimates the parameters of some data from a specified distribution, hence it requires the mean and sd for the corresponding normal distributions. You could edit the code and swap these for other distributions, but they must be parametric. It is often perfectly reasonable to assume data are from some parametric distribution, even if its not the normal distribution, although it does a pretty good job in most cases. One thing you can do is feed MixSIAR the raw isotope data and let it fit the corresponding normal distribution instead of specifying the mean/sd.

Personally I don’t really believe in non-parametric data, at least not for linear data quantified using instrumentation and when we want to estimate meaningful parameters. There is almost always a suitable parametric distribution (or combination of them) for them.

Best wishes

Andrew
--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/





On 25 Oct 2019, at 09:22, chbrax <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Brian,

MixSIAR offers the option to use summary data as input data. This must be in provided as mean and the standard deviation (SD). However, my data is not-normally distributed. Hence non-parametric statistics must be applied. This means that summary statistics can only be provided as median. As a measure of dispersion, I use the Median Absolute Deviation (MAD). The MAD is commonly referred to be a non-parametric analogue to the standard deviation. Hence it is also often used in the same way as the standard deviation. In publications, summary statistics are therefore shown as “median+/-MAD”.

My question in this regard is: Can the median and the MAD be used as summary statistic input data for MixSIAR instead of the mean and the SD?

From my experience, a considerable share of ecological data is not-normally distributed. However, many researchers still seem to use parametric tests (using mean+/-sd) instead of non-parametric tests (using median and indicating the 25th and 75th percentile, IQR, MAD,…). I assume this may also be the case for isotope data in food webs. As I have learnt, MixSIAR can summarize output data as median and 95% CI. I therefore hope that MixSIAR may also provide a solution for non-parametric input data.

Thanks very much for your reply!

Cheers,
Chris

**Comment by chbrax** [comment]
Thanks a lot, Andrew, for your very quick reply! Indeed I assumed approximate normal distribution when running my data in MixSIAR because the non-normality is caused by only 1-2 outliers (but which - by their nature - have a quite strong influence on the _mean_). I am also aware that the results in this case will always be approximations and they have to interpreted as indicative and not as absolute (which is anyway never the case). For my case using data from a soil labeled with stable isotopes and using isotope ratios in plants grown on these soils, it is absolutely fine to "only" have indicative results.

I already expected that it may most probably not be possible to use non-parametric input data because medians are not additive and MixSIAR is designed to add up distributions to equal 1. However, as an absolute newcomer to MixSIAR, I hoped that there might be a workaround :).

Thanks again!

**Comment by brianstock** [comment]
Also, note there is a slight difference between what MixSIAR assumes about the source and mix data. Both are assumed to be normally distributed, but the mix data are assumed to arise as a linear combination of the (normally distributed) sources, so by the Central Limit Theorem we expect a normal distribution. For this reason, using compositional (%) tracer data - as the case for fatty acids - is not too much of a concern. For more, see [Supp 2](https://dfzljdn9uc3pi.cloudfront.net/2018/5096/1/articleS2.pdf) in the PeerJ article. 

I'd agree with Andrew that letting MixSIAR fit the source mean + SD (i.e. the "raw" source data option) instead of providing the mean and SD would be best. 

Another thing to consider: if you have covariates that explain some of the variability in mix or source data, that may help. For example, if you have two sub-groups and include this variable in the model, MixSIAR assumes that each sub-group's tracer values are normally distributed, not necessarily the aggregate.

**Comment by chbrax** [comment]
Thank you, Brian - very helpful addition to Andrew!
