### ISSUE TITLE
Warnings at end of process output

### ISSUE THREAD

**Issue by MDelongWSU** [brianstock/MixSIAR#190]
After running process output in mixsiar, I am receiving multiple warning messages " In cor(X, use = "pairwise.complete.obs") : the standard deviation is zero".  Prior to the warnings, I am also getting the message "Error in unite(., st.part, part, statistic, sep = ".") :   could not find function "unite".  Not certain which file(s) are the problem.

**Comment by RoisinMcCallum** [comment]
MDelongWSU, did you find the solution to this? I an having the same issue. Thanks

**Comment by MDelongWSU** [comment]
No I haven't been able to sort it.  Thinking it's time to wander to IT and find someone who is very fluent in R.

**Comment by RoisinMcCallum** [comment]
I thought maybe it had something to do with me moving from mac OS to windows. I prefer to use mac but am now using RStudio on windows and it seems to work better.

I also deleted my .csv files are resaved from my raw data (.xlxs) and now I do not get the  "Error in unite(., st.part, part, statistic, sep = ".") : could not find function "unite" error. but still have the " In cor(X, use = "pairwise.complete.obs") : the standard deviation is zero". warnings. Not sure what to do about them.. please post if you find the solution

**Comment by brianstock** [comment]
Zero standard deviation warnings make me wonder: what is your sample size? Or if you're including factors, what is your sample size for each factor combination?

**Comment by MDelongWSU** [comment]
I was running the basal source contribution to primary consumers. I ran these same data in Mixsiar without issue about 5 months ago.  The basal sources file includes seven sources with a sample size of three for all sources.  The primary consumer file includes seven benthic invertebrates with five taxa having a sample size of three and two with a sample size of two.

**Comment by MDelongWSU** [comment]
I should add that there are no factors are used.  The data are for a single site.

Mike

**Comment by RoisinMcCallum** [comment]
Hi Brian,

Thanks for your response. I am using MixSIAR to estimate vegetation source contributions to sediment organic matter using 13C and 15N tracers. I have two factors : Date (2 levels) and subregion (6 levels). Sources are in 3 levels (1 source set for 2 subregions) and are not separated by Date.

Within each of the subregions, I have 15 reps per date. Sources have a minimum of 3 reps, though this may increase as I aggregate the sources through the model interations, is it an issue to have different number of reps per source within one model? There is no reason, that I can see, that my data is giving 0 standard deviation

I think my issue stems from my understanding of fixed/random factors and nesting factors – I had assumed my factors were fixed and not nested, though after rereading the model description, I think they are both random factors and subregion is nested within date.

Thanks for your help clarifying these issues.
Rosh

**Comment by VirginiaMorera** [comment]
Hi, 

I have encountered the same problem. These are the warnings I get: 

    Warning messages: 
    1: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero 
    2: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero 
    3: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero 
    4: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero 
    5: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero 
    6: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero 
    7: Removed 300 rows containing missing values (geom_bar).  
    8: In cor(as.matrix(X[, -c(1, 2), drop = FALSE])) :   the standard deviation is zero 
    9: Removed 2 rows containing missing values (geom_point).  
    10: Removed 6 rows containing missing values (geom_point).

My dataset consists of 100 observations in 10 groups (10 obs each), group is set as a fixed factor, there are no random factors or continuous variables, I've got 3 tracers and 3 sources. Sources are entered as means and SDs, and there's discrimination info but not concentration dependence, and I'm using both process and residual error. 

[Here's](https://www.dropbox.com/s/2gn4knn5gehbd80/diagnostics_both.pdf?dl=0) a link to the diagnostics plots and [here's](https://www.dropbox.com/s/7bljopphz7yex65/issue_env.RData?dl=0) the environment with the necessary data to reproduce the issue.

**Comment by RoisinMcCallum** [comment]
Hi, I had to reread the definition for fixed and random factors for mixsiar. They are different from what ecologists use those terms for statistically. What I thought were fixed factors, were actually random under the model definitions.



Sent from my iPhone

On 6 Mar 2020, at 20:13, VirginiaMorera <notifications@github.com> wrote:

﻿

Hi,

I have encountered the same problem. These are the warnings I get:

Warning messages:
1: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero
2: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero
3: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero
4: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero
5: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero
6: In cor(X, use = "pairwise.complete.obs") :   the standard deviation is zero
7: Removed 300 rows containing missing values (geom_bar).
8: In cor(as.matrix(X[, -c(1, 2), drop = FALSE])) :   the standard deviation is zero
9: Removed 2 rows containing missing values (geom_point).
10: Removed 6 rows containing missing values (geom_point).


My dataset consists of 100 observations in 10 groups (10 obs each), group is set as a fixed factor, there are no random factors or continuous variables, I've got 3 tracers and 3 sources. Sources are entered as means and SDs, and there's discrimination info but not concentration dependence, and I'm using both process and residual error.

Here's<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Fs%2F2gn4knn5gehbd80%2Fdiagnostics_both.pdf%3Fdl%3D0&data=02%7C01%7Cr.mccallum%40ecu.edu.au%7Cce06e68ead174c4d24a108d7c1c7c35f%7C9bcb323d7fa345e7a36f6d9cfdbcc272%7C1%7C1%7C637190936037187425&sdata=n9RwZlRjbuIDTIAc5nBLaLgJpU%2FyLDhfdGH%2BjfW68GQ%3D&reserved=0> a link to the diagnostics plots and here's<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Fs%2F7bljopphz7yex65%2Fissue_env.RData%3Fdl%3D0&data=02%7C01%7Cr.mccallum%40ecu.edu.au%7Cce06e68ead174c4d24a108d7c1c7c35f%7C9bcb323d7fa345e7a36f6d9cfdbcc272%7C1%7C1%7C637190936037197417&sdata=BdyYReuNcDrDFLkrF4GrMPpNo5VJec0yB31aE70jRYM%3D&reserved=0> the environment with the necessary data to reproduce the issue.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrianstock%2FMixSIAR%2Fissues%2F190%3Femail_source%3Dnotifications%26email_token%3DAEBSOF4CHUBTDBRZJ5BLV3LRGDSF7A5CNFSM4JKMW5VKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOBE2EA%23issuecomment-595741968&data=02%7C01%7Cr.mccallum%40ecu.edu.au%7Cce06e68ead174c4d24a108d7c1c7c35f%7C9bcb323d7fa345e7a36f6d9cfdbcc272%7C1%7C1%7C637190936037197417&sdata=n3QUTjo9JVJ78P3UdRt2MQTMAoP25FI3k27mu4H05VM%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEBSOF6EFOZH3ISYPPR4EBLRGDSF7ANCNFSM4JKMW5VA&data=02%7C01%7Cr.mccallum%40ecu.edu.au%7Cce06e68ead174c4d24a108d7c1c7c35f%7C9bcb323d7fa345e7a36f6d9cfdbcc272%7C1%7C1%7C637190936037207412&sdata=M5sAvYEDZcT53A4SZUAWJ2g7I4fkig8g%2FMVgKnaXj4Q%3D&reserved=0>.

________________________________

This e-mail is confidential. If you are not the intended recipient you must not disclose or use the information contained within. If you have received it in error please return it to the sender via reply e-mail and delete any record of it from your system. The information contained within is not the opinion of Edith Cowan University in general and the University accepts no liability for the accuracy of the information provided.

CRICOS IPC 00279B
RTO PROVIDER 4756

**Comment by MDelongWSU** [comment]
I upgraded to R version 3.6.2 patched and what you show below went away.

**Comment by VirginiaMorera** [comment]
Thanks you both for the feedback! I've looked over the code and info on the manual and peerJ paper and I don't think the issue is with the type of factors (fixed-random), and I am already using R 6.3.2, so I don't think those are the issues! 

My session info

    R version 3.6.2 (2019-12-12)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 18363)

**Comment by AndrewLJackson** [comment]
Hi

No. The definitions are entirely consistent with terminology from standard linear models. If there is any confusion it’s cultural within the ecology analysis sphere of what constitutes a fixed and random factor. The former is on the mean, the latter on error. Granted things get a bit more tricky when using eg JAGS to fit the models and the random factors can appear on the equations used to define the means but the effect is the same.

Best wishes
Andrew



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 6 Mar 2020, at 13:03, RoisinMcCallum <notifications@github.com> wrote:

﻿Hi, I had to reread the definition for fixed and random factors for mixsiar. They are different from what ecologists use those terms for statistically. What I thought were fixed factors, were actually random under the model definitions.



Sent from my iPhone

On 6 Mar 2020, at 20:13, VirginiaMorera <notifications@github.com> wrote:

﻿

Hi,

I have encountered the same problem. These are the warnings I get:

Warning messages:
1: In cor(X, use = "pairwise.complete.obs") : the standard deviation is zero
2: In cor(X, use = "pairwise.complete.obs") : the standard deviation is zero
3: In cor(X, use = "pairwise.complete.obs") : the standard deviation is zero
4: In cor(X, use = "pairwise.complete.obs") : the standard deviation is zero
5: In cor(X, use = "pairwise.complete.obs") : the standard deviation is zero
6: In cor(X, use = "pairwise.complete.obs") : the standard deviation is zero
7: Removed 300 rows containing missing values (geom_bar).
8: In cor(as.matrix(X[, -c(1, 2), drop = FALSE])) : the standard deviation is zero
9: Removed 2 rows containing missing values (geom_point).
10: Removed 6 rows containing missing values (geom_point).


My dataset consists of 100 observations in 10 groups (10 obs each), group is set as a fixed factor, there are no random factors or continuous variables, I've got 3 tracers and 3 sources. Sources are entered as means and SDs, and there's discrimination info but not concentration dependence, and I'm using both process and residual error.

Here's<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Fs%2F2gn4knn5gehbd80%2Fdiagnostics_both.pdf%3Fdl%3D0&data=02%7C01%7Cr.mccallum%40ecu.edu.au%7Cce06e68ead174c4d24a108d7c1c7c35f%7C9bcb323d7fa345e7a36f6d9cfdbcc272%7C1%7C1%7C637190936037187425&sdata=n9RwZlRjbuIDTIAc5nBLaLgJpU%2FyLDhfdGH%2BjfW68GQ%3D&reserved=0> a link to the diagnostics plots and here's<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Fs%2F7bljopphz7yex65%2Fissue_env.RData%3Fdl%3D0&data=02%7C01%7Cr.mccallum%40ecu.edu.au%7Cce06e68ead174c4d24a108d7c1c7c35f%7C9bcb323d7fa345e7a36f6d9cfdbcc272%7C1%7C1%7C637190936037197417&sdata=BdyYReuNcDrDFLkrF4GrMPpNo5VJec0yB31aE70jRYM%3D&reserved=0> the environment with the necessary data to reproduce the issue.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrianstock%2FMixSIAR%2Fissues%2F190%3Femail_source%3Dnotifications%26email_token%3DAEBSOF4CHUBTDBRZJ5BLV3LRGDSF7A5CNFSM4JKMW5VKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOBE2EA%23issuecomment-595741968&data=02%7C01%7Cr.mccallum%40ecu.edu.au%7Cce06e68ead174c4d24a108d7c1c7c35f%7C9bcb323d7fa345e7a36f6d9cfdbcc272%7C1%7C1%7C637190936037197417&sdata=n3QUTjo9JVJ78P3UdRt2MQTMAoP25FI3k27mu4H05VM%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEBSOF6EFOZH3ISYPPR4EBLRGDSF7ANCNFSM4JKMW5VA&data=02%7C01%7Cr.mccallum%40ecu.edu.au%7Cce06e68ead174c4d24a108d7c1c7c35f%7C9bcb323d7fa345e7a36f6d9cfdbcc272%7C1%7C1%7C637190936037207412&sdata=M5sAvYEDZcT53A4SZUAWJ2g7I4fkig8g%2FMVgKnaXj4Q%3D&reserved=0>.

________________________________

This e-mail is confidential. If you are not the intended recipient you must not disclose or use the information contained within. If you have received it in error please return it to the sender via reply e-mail and delete any record of it from your system. The information contained within is not the opinion of Edith Cowan University in general and the University accepts no liability for the accuracy of the information provided.

CRICOS IPC 00279B
RTO PROVIDER 4756

**Comment by RoisinMcCallum** [comment]
Apologies Andrew, I did not mean to confuse things.
They are different from what I have been taught as random and fixed factors – but you are completely correct, it is likely cultural/my limited statistical understanding. It sounds like the factor assignment is not the issue in this case anyway.

Cheers
Rosh

**Comment by VirginiaMorera** [comment]
Thanks Andrew, that's what I thought. Any idea of what the warnings can mean, then? I see in the diagnostics that the density plots for ilr.fac[1,1] and ilr.fac[1,2] look like this 
![imagen](https://user-images.githubusercontent.com/11058769/76201163-25f54680-61f3-11ea-9776-540ad8b0c919.png)
which I guess would be causing the SD to be 0 (one of the warnings I get) and probably the missing values in geom_bar and geom_point too (other warnings of the list I shared), but I'm not sure what's causing this. There's 22 obs in the first level of my fixed factor, with SD 0.49, 0.47 and 1.77 in each of the tracers respectively... I don't quite get how the ilr transformation works although I've tried to understand it from the PeerJ paper, so I can't interpret what this means! 

Thanks for your help

**Comment by ericward-noaa** [comment]
I think all the warnings messages about correlations can be safely ignored. With 2 sources / 2 factors, you have 4 ilr parameters being estimated. For identifiability, the first for each group on each isotope are set to 0 -- ilr.fac[1,1] and ilr.fac[1,2]. Remember this is in ILR space - so when these parameters are transformed to normal space to get proportions, the estimates for predictions aren't 0. 

The warnings not coming from MixSIAR, but trying to call a correlation matrix on the estimates that include a bunch of 0s. For example you get the same thing with 

df = data.frame(rnorm(100),rep(0,100))
cor(df)

**Comment by brianstock** [comment]
Yes, like Eric said the first levels of `ilr.fac1` and `ilr.fac2` are set to 0 when they are fixed effects. You can also consider the `ilr.fac1` as "offset" terms from the overall intercept, `ilr.global`. Then `ilr.global[src]` represents the first level of `ilr.fac1` (`ilr.fac1[1,src]`), and `ilr.global + ilr.fac1[2,src]` is the second level.

The model is correctly specified but the output plot function from `ggmcmc` is trying to calculate nonsensical correlations.
