### ISSUE TITLE
MixSIAR Hierarchical structure question

### ISSUE THREAD

**Issue by SejerMeyhoff** [brianstock/MixSIAR#191]
Hello folks,

First of all, thank you all for making this package so accessible. I am new to R and isotopes and the working examples were really helpful.

I am trying to put together my script to run MixSIAR in order to estimate the diet of sharp-tailed grouse using 10 primary feathers from each bird and two tracers, N15 and C13 with concentration dependence. 

My question concerns the hierarchical structure and how I should load my mixture data. I have three factors: 

**Class** - age*sex of the birds, there are 4: adult female, adult male, juvenile female, juvenile male

**Primary** - each bird has tracer data for primaries 1-10. They represent a time series across the birds’ molting period from May (P1) to October (P10). 

**Season** - I divided the molting period into three seasons: spring (May-June: P1-P3), summer (July-Aug: P4-P6), fall (Sept-Oct: P7-P10) and have different source values for my three diet groups (arthropods, native plants, and agricultural crops) for the different seasons. Truth be told, the only one that varies is the ‘arthropods’ group, the other two have identical values throughout the seasons (not enough samples). But I would like to incorporate the variability in arthropod isotope values through the seasons if I can. 

I would like to run the model so that MixSIAR estimates the diet represented by each Primary (1-10) for each Class of bird, using the different diet group values for the corresponding seasons. 

So that I end up with a diet proportion estimate for each Primary for each Class. 

My problem is I am having a hard time wrapping my head around the hierarchical structure, how to nest them appropriately in MixSIAR, how to reflect that in the script, and which should be treated as random effects. 

This is my guess.. Primary nested within Class makes sense to me, but how do I fit season into it? Or would it be easier to just run the model once for each season? 

mix <- load_mix_data(filename="grouse_consumer", 
                     iso_names=c("d13C","d15N"), 
                     factors=c("Class","Primary","Season"), 
                     fac_random=c(TRUE,TRUE,FALSE), 
                     fac_nested=c(FALSE,TRUE,TRUE), 
                     cont_effects=NULL)

Thanks in advance. 

Sejer Meyhoff

**Comment by SejerMeyhoff** [comment]
I see my first mistake, that MixSIAR doesn't handle more than 2 random/fixed effects. So is my best solution just to run the model once for each season?

**Comment by brianstock** [comment]
Since you have multiple samples per individual bird, it seems like you have another important factor: Bird. It probably makes sense to include this as a random effect, assuming you have at least a few birds for each combination of the other factors.

I wouldn't include both Season and Primary because they're effectively the same thing: time. I'd either:
  a) Calculate what time period each primary represents, then include that as a continuous effect. The result would be akin to the alligator example, an estimate of diet proportion as a (roughly, in ILR-space) linear function of time. If you think the diets change more cyclically, consider the models in [Parnell et al. (2013)](https://onlinelibrary.wiley.com/doi/abs/10.1002/env.2221).
  b) Include Season as a fixed effect (which also allows you to include the different arthropod data). 
Whichever you choose, you can also add Class or Bird, assuming you have birds in all classes in all seasons.

If you have a high sample size for all bird-class-season combinations, you could relatively easily modify MixSIAR to allow for all 3 effects. While MixSIAR can only include 2 effects at a time, you can compare a Class-Bird model to a Season-Class model to a Season-Bird model, ...

Finally, the model structure depends on what hypotheses you want to evaluate.

**Comment by SejerMeyhoff** [comment]
Thank you for your reply Brian,

Your suggestion regarding Season and Primary makes a lot of sense, and I have calculated a Julian date for each primary and included that as a continuous variable. 

I have since simplified my sources so now I just have a single value and SD for each diet source. I didn’t feel that the differences (and sample sizes) really justified it in the end. 

I think I get what you are saying by suggesting that I include Bird as a random factor, however, when I load the data:

mix <-load_mix_data(filename = "grouse_consumer.csv",       
               iso_names =c("d13C","d15N"),
               factors =c("Bird_ID","Class"), 
               fac_random = c(TRUE,FALSE),  
               fac_nested =c(FALSE,TRUE),  
               cont_effects ="Julian_date") 

It gets rid of 284 lines (out of 390) in the biplot. I am not sure I understand why, and how that affects the model. But the output does not include a density plot with Julian date on the x axis, like it does when I just include Class as a fixed effect. Instead it gives me a density plot for each bird, which I don’t really need.

Some birds have primaries missing, and juvenile birds (2 of the classes) have different primary-> Julian date than adult birds (the other 2 classes). The Bird_ID column is numeric. What is causing it to drop the 284 lines?

I am simply trying to evaluate diet proportion changes through time for each class. So initially it made sense to me to not include Bird as a variable. Now I am not sure. 

Thanks!

**Comment by brianstock** [comment]
I'm not sure what you mean "It gets rid of 284 lines in the biplot." Do you mean data points? Is there any error/warning message? It's hard for me to tell what's going on without more information. It's possible the plots aren't useful but the model is correct. But when the biplot looks funny or generates error/warning messages, it often means the model is not correctly specified (given the data).

I have not written a plotting function for your case (1 fixed effect + 1 random effect + 1 continuous effect). See https://github.com/brianstock/MixSIAR/issues/180 for code to recreate the Length + Individual alligator model plot ([Fig 6 in PeerJ paper](https://peerj.com/articles/5096/#fig-6)). In your case you probably want a 4-panel plot (1 for each class), where each looks like that Fig 6. You'll have to modify the above code to add in the `ilr.fac1` term for each class in line 99.

If you don't include a random effect of Bird, then you're assuming that all primaries for a class are independent. This is not true since several are from the same birds. It's a case of pseudoreplication, as your effective sample size should be lower than if you had the same number of feathers but all from different birds.

**Comment by SejerMeyhoff** [comment]
Sorry for not being more clear. When generating the biplot it gives me the warning "Removed 235 rows containing missing values (geom_point)." 

Thanks for the reference to that code. I'm not sure I have the R skills to modify it, but I will give it a go. 

And yes, that makes sense about pseudoreplication. Thanks for pointing that out.

**Comment by SejerMeyhoff** [comment]
I can’t figure out why the biplot is giving me the error “Removed 235 rows containing missing values (geom_point)”. I don't think it's affecting the model, but I would like to be sure. I tried to back calculate the variables like you did in #147 . 

Diagnostics show 1671 variables
•	1170 feather proportions (390 feathers x 3 sources)
•	12 Class proportions (4 classes x 3 sources)
•	1 Bird_ID SD
•	3 global level proportions (3 sources) *although I don't see these in the output summary?
•	2 epsilon terms (multiplicative error)
•	1 Deviance 
•	80 ilr.fac1 (40 birds x 2 sources)
•	8 ilr.fac2 (4 classes x 2 sources)
•	390 log-likelihoods (1 per mix datapoint)

= 1667. What did I miss? If I’m on the right track, I guess it means its safe to say that the model is using all the datapoints? 

So, to be clear, my ‘consumer’ csv has the following headers: Bird_ID, Class, Julian_date, d15N, d13C.
 - Bird_Id is numeric, ranging form 3 – 200 (40 unique values)
 - There are 19 unique Julian dates, ranging between 121-204. 
 - There are 4 different classes: FAHY (15), FHY (9), MAHY (8), MHY (8). (total 40)
 - All rows have a d15N and d12C value. 

Also, am I understanding the nested function correctly, that I should nest my ‘classes’ within ‘bird_id’? So that each bird is treated individually?

**Comment by SejerMeyhoff** [comment]
Update: I resolved to run a separate model for each class with Bird_ID as fixed and Julian date as a continuous variable. And I was able to coerce the alligator script to output a global time-series estimate of diet proportions for each class from that output. Thanks for referring me to that code!
