### ISSUE TITLE
Could the contribution of base sources to top predator be calcluated by MixSIAR?

### ISSUE THREAD

**Issue by Johnme24** [brianstock/MixSIAR#192]
Hi Brian,
Thanks for the MixSIAR package shared, I've benefited a lot, really appreciate that…
As a new MixSIAR user,  I hope this question would not be too native, but it confused me indeed, for not referring to revelant information in Manual.pdf.
First, I woder if it's feasible to calculate the contribution of base souces to top predators, such as reckoning plankton contribution to piscivorous  fish.  I read a literature< Feeding ecology of fishes associated with artificial reefs in the northwest Gulf of Mexico> before, the author estimated the realtive contribution of phytoplankton and microalgae to the trigerfish and red snappers,however, there's no direct trophic relationship between the consumer and sources. Even TEF values added, the source polygon can't include the mixture. As the manual wrote: If the mixture data are well outside the source polygon, you have a serious violation of mixing model assumptions. So I get a little of confused!
Besides, I wanna to know if there's only 2 sources, how to establish a ploygon and carry out the subsequent reckoning .
The access of the refered aritcle,https://doi.org/10.1371/journal.pone.0203873 
Thanks for reading the words above , looking forward to your reply.@brianstock

**Comment by ChrisHarrod** [comment]
I’m nothing to do with the package, but I’ll butt-in :)

Many people do this by adding the TDFs, but as you say, it’s important to check that the data then fall in the mixing polygon. That they don’t might mean that you are underestimating the trophic position of your consu,ers, or that the baseline is out of sync with the higher trophic levels (this happens annoyingly often). We tend to use this approach to estimate the relative contribution of pelagic and benthic C to rocky reef fish but instead of using the phyto and macroalgae, we use primary consumers that we are 99 % sure are obligate feeders on the different basal resources e.g. bilvaves (phyto) v grazing gastropods (magroalgae).

Cheers
Chris


><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><>
Professor Chris Harrod
(Fish & Aquatic Ecology)

Email: chris@harrodlab.net<mailto:chris@harrodlab.net>
Twitter: @chris_harrod
www.harrodlab.net<http://www.harrodlab.net/>

Fish and Stable Isotope Ecology Laboratory
Instituto de Ciencias Naturales Alexander von Humboldt

Universidad de Antofagasta Stable Isotope Facility
Instituto de Antofagasta

Universidad de Antofagasta,
Avenida Angamos 601, Antofagasta, Chile

Núcleo Milenio INVASAL, Concepción, Chile


Chile Mobile: +56 9 7399 7792
Chile Office: +56 55 2637400

<>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <><

**Comment by Johnme24** [comment]
Much thanks, dear Professor Harrod,  I probably understand what you conveyed. Next, I think I may need to read more articles on this theme !
