### ISSUE TITLE
Trying to compare diet structures of two populations: running them together and separately yielded very different results! 

### ISSUE THREAD

**Issue by christina-cheung** [brianstock/MixSIAR#193]
Hi, I am pretty new to R and mixing model and I am hoping someone can help me out here~ 

I am trying to do something very straightforward, compare the diets of two populations, who have access to the same set of sources, with the same concentration and fractionation factor, basically all conditions are the same. And so I tried running them in MixSIAR using the "Geese" script. I also then run the two populations separately (one at a time - kind of like the "killer Whales" script, except just using uninformative priors). The results are very different. I am wondering why are the results so different, and also if one way (running them together or separately) is better than the other? 

Many thanks!

**Comment by MaartenWynants** [comment]
It is quit normal that your output will be different given the completely different structure of the models. Your mixture is different, you have an informative vs. uninformative prior, etc. How are the diagnostics using your two different models? You could also use the compare_model tool to check which structure is behaving best. Have you tried using population as a fixed categorical while keeping your prior? This way you can run everything in one model, keep the same prior and  calculate the source contribution to your two different populations. 

Cheers,
Maarten

**Comment by christina-cheung** [comment]
Dear Maarten, 
Thank you for your reply! I hope I am understanding your comment correctly... 

I'm setting my different population ("site") as fixed by setting fac_random as false. I didn't run with any specific priors (just alpha.prior=1). 

mix <- load_mix_data(filename=mix.filename,
                     iso_names=c("d13C","d15N"),
                     factors="Site",
                     fac_random=FALSE,
                     fac_nested=FALSE,
                     cont_effects=NULL)

And here's the result:

                   Mean    SD  2.5%    5%   25%   50%   75%   95% 97.5%
p.1.C3C4Mixed    0.005 0.005 0.000 0.000 0.001 0.003 0.006 0.016 0.019
p.2.C3C4Mixed    0.041 0.054 0.000 0.000 0.002 0.010 0.067 0.157 0.168
p.1C3Herbivores 0.004 0.005 0.000 0.000 0.001 0.003 0.006 0.014 0.018
p.2.C3Herbivores 0.018 0.025 0.000 0.000 0.002 0.008 0.021 0.080 0.097
p.1.C3Plants     0.171 0.095 0.003 0.006 0.055 0.226 0.240 0.253 0.257
p.2.C3Plants     0.187 0.106 0.005 0.010 0.095 0.198 0.279 0.337 0.349
p.1.C4Herbivores 0.215 0.319 0.000 0.000 0.004 0.010 0.552 0.833 0.886
p.2.C4Herbivores 0.189 0.171 0.001 0.001 0.016 0.166 0.320 0.489 0.543
p.1.C4Omnivores  0.008 0.009 0.000 0.000 0.002 0.005 0.011 0.028 0.034
p.2.C4Omnivores  0.116 0.101 0.000 0.000 0.008 0.124 0.182 0.296 0.329
p.1.C4Plants     0.596 0.239 0.050 0.106 0.378 0.741 0.753 0.768 0.774
p.2.C4Plants     0.449 0.173 0.071 0.122 0.345 0.468 0.552 0.740 0.766

And then I tried to run the two populations on its own, here's the result of just the second population:
                   Mean    SD  2.5%    5%   25%   50%   75%   95% 97.5%
p.2.C3C4Mixed    0.032 0.027 0.001 0.002 0.011 0.025 0.046 0.087 0.104
p.2.C3Herbivores 0.042 0.028 0.002 0.005 0.019 0.039 0.062 0.091 0.102
p.2.C3Plants     0.103 0.072 0.003 0.007 0.041 0.092 0.152 0.235 0.257
p.2.C4Herbivores 0.259 0.201 0.017 0.028 0.103 0.206 0.372 0.679 0.764
p.2.C4Omnivores  0.047 0.034 0.001 0.003 0.019 0.042 0.070 0.112 0.124
p.2.C4Plants     0.517 0.181 0.066 0.132 0.423 0.560 0.651 0.744 0.766

The proportions are quite different in terms of the means (and medians). I'm most concerned about the proportion between C4 herbivores and C4 omnivores, it went from 18.9% versus 11.6% to 25.9% vs. 4.7%. How do I decide which way is better? Would compare_model allow me to run the two populations individually?  My understanding is that it only allows you to play with different factors, but with the same set of consumer. 

I hope this make sense. Please let me know if you would like me to clarify!
Cheers,
Chris

**Comment by brianstock** [comment]
Do you mean you're concerned about the *difference* between p.2.C4Herbivores and p.2.C4Omnivores? If you are, see https://github.com/brianstock/MixSIAR/issues/21 for an example of how to get a full posterior for the difference between 2 proportions.

Those estimates don't look that different to me... when you say that p.2.C4Herbivores went from 18.9% to 25.9%, that's meaningless without acknowledging how precise those estimates are. The 95% CI goes from 0.1-54.3% to 1.7-76.4%. Unless your sample sizes (both mixture and sources) are quite high, I wouldn't expect a typical 2-tracer mixing model to resolve a difference less than 5%.

In order to compare models using information criteria (WAIC/LOOic/DIC), you need to have the same data. So no, you can't compare running your two sites individually vs. one model using site as a factor.

Option 1: fit both sites in the same model using Site as a fixed effect, you only estimate one mixture covariance matrix. Option 2: run separate models for each Site, you end up estimating two mixture covariance matrices. This makes sense if your two sites have very different variance or correlation. If your two sites have similar variances and correlations, option 2 means you estimate more (unnecessary) parameters and get less precise estimates. I think this is more often the case, which is why I generally recommend option 1.

**Comment by christina-cheung** [comment]
Dear Brian, 

Thank you so much for replying! Sorry for not being clear in phrasing my question. I understand the means are not precise and I should use the range. I am mostly intrigued by the changes in proportion between the different sources in the two different models. So for example in the first model, population 2 ate roughly 40% (this is based on the means, but the proportions are kind of similar throughout) more C4 herbivores than C4 omnivores, and in the second model, population 2 ate 80% more C4 herbivores than C4 omnivores. Let me give a little background to these data. Populations 1 and 2 are two groups of (archaeological) humans living in the same site, and I'm hoping to use mixing models to explain the differences in their d13C and d15N values. The difference in proportions could translate to very different animal husbandry practices. In this case, would you still recommend using option 1 (fit both sites in the same model)?

Also when you say covariance matrices/ correlations, what does it mean biologically? For example, do you mean if the two groups are competing for the same pool of limited resources? 
Thanks in advance for your help!!

**Comment by AndrewLJackson** [comment]
Hi brian

Im diving in to this a bit cold, and ive not looked in detail, but if DIC is mathematically equivalent to AIC then you can simply add them together for subsets of a dataset. So if you have response variable Y and a categorical explanatory variable X with two levels A and B then you can compare the following

AIC(single_model)

AIC(separate_model_group_A) + AIC(separate_model_group_B)

This is because the log likelihoods are additive as are the number of parameters. The code below illustrates this


## -- start code --

set.seed(1)

# make a lot of data so the two groups have almost identical variance
n <- 10^3

# make same Y data for this example which actually circumvents the sample
# size setting above since now we are forcing the data to have the same
# variance because the data ARE the same.
Y <- rep(rnorm(n), 2)

# make two categories
X <- c(rep("A", n), rep("B", n) )

# fit one linear model
m1 <- glm(Y ~ X)

# fit two linear models for each group seperately. In this case
# we need to fit two models with an intercept each. In other cases, they
# might have another linear covariate in common in an ANCOVA style analysis.
m2_A <- glm(Y ~ 1, subset = X == "A")
m2_B <- glm(Y ~ 1, subset = X == "B")


# The AIC of the single fit model
AIC(m1)

# The AIC of the combined model has a value +2 over the single fit above
# owing to there being exactly 1 more parameter arising from the additional
# variance parameter.
AIC(m2_A) + AIC(m2_B)


## -- end code --

Like  I said, I might have gone off on a tangent as im jumping in, so apologies if ive gone awry. Also, it may well be the case the the calculation of deviance is not additive in the same way as AIC and I haven’t looked.

Best wishes

Andrew


--
Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

**Comment by christina-cheung** [comment]
Dear Andrew and Brian, 

Thank you for your answers!! Forgive me but I am still a little confused... 
Let me try to phrase my question better this time:

I am an archaeologist trying to quantify (and eventually compare) the past diets of two groups of humans. These two groups of people are from the same site, and therefore likely have access to the same sets of resources (same source). I get different results when I a) fit the two groups of humans in the same model (group as fixed effect), and b) run each group separately. The difference between these two different approaches are big enough that I want to understand which is the better approach. Brian mentioned that when I tried to fit two groups in one model I only work with one mixture covariance matrix so there will be less error. However, I don't understand how does a "mixture covariance matrix" translate in biological sense. Does it mean the two groups compete for resources? Or is it just a mathematical notion? Many, many thanks in advance!!

**Comment by brianstock** [comment]
Hi Chris,

"Mixture covariance matrix" refers to the correlation and variance of the
human tracer data. If the data for the two groups have similar variances
and correlations, then I'd fit one model with group as a fixed effect
because it fits one correlation and variance term per tracer (shared by
both groups). If your groups have very different variances, then it may be
better to run separate models as this will allow the variance of each group
to be different. Generally, estimating fewer parameters is preferred,
unless there is a need (e.g. if the variances are quite different).

**Comment by christina-cheung** [comment]
Thank you so much for your explanation!!
