### ISSUE TITLE
R Studio "not responding" while running jags model

### ISSUE THREAD

**Issue by nlaroche129** [brianstock/MixSIAR#201]
Background: My dataset has 7 sources and 289 consumer samples that have one fixed factor (season, so 4 levels). I have 29 individuals with serial samples (whisker subsections) but am not currently running the individuals as a factor. And I am using an informative prior. I am currently using a "very long" run. I have a mac book pro with OS10.14.6 and R v 3.6.1. I am not using the GUI, just code.

Sometimes when I run this model, r will stop responding and give me the colored death circle (high tech mac wording). I have had success running the model, it took 56h47m. Is there a way to avoid these failed runs (i.e. running the data in smaller runs in parallel)? Any clue why it may be happening? I looked at the processor power when running the last time and it was using about 2.75gb of ram the whole 56+ hours.

**Comment by brianstock** [comment]
Sorry for the slow reply...

Sounds like you just have a dataset+model that takes a lot of computing. I'd always use a short "test" run first to make sure the model is set up correctly, but sounds like that's already the case. And for any model that takes that long, I'd run them in the terminal directly instead of R Studio because it's more lightweight. It's possible that R (or R Studio) can stop responding even though it's still running and will complete successfully. 

Runtime increased quite a bit when I changed MixSIAR to be multivariate ([v3.0.0](https://github.com/brianstock/MixSIAR/releases/tag/3.0.0) in Oct 2015). In an ideal world, MixSIAR would run the MCMC chains in parallel... see issue https://github.com/brianstock/MixSIAR/issues/146. From that discussion, sounds like 1) it could be possible to get that working if you make a personal copy of MixSIAR and modify, but 2) probably tricky and not worth your time. Short of getting parallel chains to work or re-coding MixSIAR in something faster than JAGS, I think you'll have to live with the long runtime. Sorry!
