### ISSUE TITLE
PROBLEM IN OPENING GUI INTERFACE 

### ISSUE THREAD

**Issue by BD2410** [brianstock/MixSIAR#205]
Good Morning, I am a student who needs this program for my final degree practices and i would like to solve some problems with the installation of mixiar_gui. 
Following the manual, once I get to step 10, and I get what's attached to the picture, the window that should appear does not appear. How could I fix it? 
Thank you very much in advance, i will wait for your answer. 
Best regards 
Esther 

![Screenshot 2020-02-10 at 12 59 42](https://user-images.githubusercontent.com/60919103/74338971-72d82f80-4da3-11ea-9b66-1487600b5081.png)

**Comment by brianstock** [comment]
Hi Esther,

Can you load `RGtk2`, `gWidgets`, and `gWidgetsRGtk2` separately? I.e.:
```
library(RGtk2)
library(gWidgets)
library(gWidgetsRGtk2)
```

What OS and versions of R + packages are you using? Hard to help without more info.

And my general advice is that if you're using this for anything that needs to be reproducible (manuscript, thesis, etc.), you should ditch the GUI and use the script version of MixSIAR.

**Comment by Fabioerc** [comment]
Dear Brian,
I am a researcher who has experienced the same problem of Esther. I followed all steps from MixSIAR manual for the installation but when run the script mixsiar_gui(), error appears:

Error in mixsiar_gui() : could not find function "mixsiar_gui"

I also tried to load RGtk2, gWidgets, and gWidgetsRGtk2 separately but when load  gWidgetsRGtk2 the "Installer GTK+ 2.18.5 (X11)" appears with the warning message: "This package requires Mac OS X 10.5 (Leopard) or higher".
I am using R version 4.0.0 (2020-04-24) -- "Arbor Day" for the recently installed Mac OS Catalina, and R Studio. 

Could you please help me to fix the problem? I would need to run MixSIAR as soon as possible for my manuscript.
Thank you very much in advance.
Best wishes,
Fabio.

**Comment by brianstock** [comment]
Hi Fabio,

I recently split the GUI, function `mixsiar_gui()`, off into its own package to live on GitHub: https://github.com/brianstock/MixSIARgui. I've updated the install/use instructions on the README pages but not in the manual. This was required for MixSIAR to remain on CRAN.

I don't know why, but it is difficult to install the required GTK+ libraries on Mac. It is really easy on Linux, and pretty easy on Windows. I don't have a Mac and am not much help... Under the [MixSIARgui Mac install instructions](https://github.com/brianstock/MixSIARgui#mac), I've posted a method that used to work a few years ago, and some links that look promising.

But really, if you're using MixSIAR for a manuscript, I strongly advise using your time to learn to use the script version instead of fighting to get the GUI installed. With a script, you have a record of commands you used to generate your results and figures. You lose this with the GUI.

Lastly, if you do manage to get the GUI working on your Mac, I'd appreciate if you can post what worked for you on the [MixSIARgui Issues page](https://github.com/brianstock/MixSIARgui/issues).

**Comment by Fabioerc** [comment]
Hi Brian,
thank you very much for your help but still does not work. I will try to use the script version.
All the best,
Fabio
