### ISSUE TITLE
Interpreting posterior density

### ISSUE THREAD

**Issue by AdamDuBour** [brianstock/MixSIAR#21]
Hello All,
   I had a few questions for any of the MixSIAR administrators or users regarding the interpretation of the posterior density plots. 
   For the plot showing global population diet proportions the Y-axis shows the "posterior density". Does this value correspond to a posterior probability for a particular source's diet proportion? For example if the distributions for sources "A" and "B" peak at 4 and 2 respectively, does that imply that there is a higher posterior probability that the mean diet proportion for source "A" is correct? Also, please correct me if I am wrong but I believe that the width of the distributions correspond to the quantiles in the summary statistics.
  Finally, how would one then interpret the "scaled posterior density" found on the plots for diet proportion by the covariates in the model?
   Thank you,
Adam

**Comment by brianstock** [comment]
Hi Adam,

The posterior densities are probability distributions for the proportion of each source.  The values of the y-axis cannot be interpreted as probabilities--probabilities are measured over *intervals* by taking the integral (area under the curve).  So yes, if the curve is higher there, then more area will be under the curve nearby.  Yes, you're right that the width of the distributions are used to calculate the quantiles.  The 95% credible interval is the middle portion of the distribution, with 2.5% of the area to the left and 2.5% of the area to the right.

Short answer: The y-axis units are pretty much meaningless in both scaled and unscaled plots.  I scaled the posterior densities because in some situations the y-axis would be very high for one source (ex. when one source is known to be close to 0, the y-axis can be very high), and you couldn't see the other sources well.  The scaled posterior densities are no longer true probability distributions, because they don't integrate to 1.  But visually they are the same, in that 95% of the area under the curve shows you 95% probability.

To demonstrate, let's say we just fit the Wolves example in MixSIAR.  
![region2](https://cloud.githubusercontent.com/assets/5124211/6453474/28d99dfc-c0f3-11e4-8fd7-4d602b5312cd.png)
In the summary statistics, we see the following line for Region 2 Deer:
```
p.Region 2.Deer           0.594 0.083 0.431 0.457 0.540 0.594 0.651 0.727 0.753
```
Above, the 2.5% and 97.5% quantiles are given as `0.431` and `0.753`.  We can report the median as 0.59 with a 95% CI of (0.43, 0.75). The MCMC chain for Region 2 Deer diet proportion is `mixsiar$jags.1$p.fac1[,2,1]`, and we can calculate the 95% CI limits with:
```
attach.jags(mixsiar$jags.1) # attach.jags(jags.1) if using mixsiar_script.r
median(p.fac1[,2,1])
quantile(p.fac1[,2,1],.025)
quantile(p.fac1[,2,1],.975)
```
If you wanted the probability that the Region 2 Deer diet proportion is greater than 0.7:
```
# Total num draws
(tot <- length(p.fac1[,2,1]))
# Num draws above 0.7
(above <- length(which(p.fac1[,2,1]>0.7)))
# Prob that the diet proportion is above 70%
(prob <- above/tot)


```
See also: http://www.sumsar.net/blog/2014/10/probable-points-and-credible-intervals-part-one/

**Comment by AdamDuBour** [comment]
Thanks for the quick reply Brian. That was extremely helpful.
-Adam

**Comment by christina-cheung** [comment]
Hi, I am trying to do this (MixSIAR v. 3.1.10.9000) but the console just says "could not find function "attach.jags"" and then the rest won't work. Or am I missing an additional package? or something else? Thanks in advance for your answer!
