### ISSUE TITLE
Consumer data paired with source data

### ISSUE THREAD

**Issue by lauriyeso** [brianstock/MixSIAR#213]
Hello! I didn´t find an example with a relation between source and consumer data like I have in my study. 
I expose my data:  I try to understand the water source for several species in an arid landscape

I  analysed d2H and d18O stable isotopes from the xilem of the plants (CONSUMER DATA)in spring and in summer. 
I analysed d2H and d18O from the soil UNDER EACH PLANT I collected at two different deephts and extracted at different temperatures (free water and crystalization water) . So, I have 4 possible sources for each individual plant. 

I would like to know the source of water of this community of plants without losing the information the soil just under the plant can give to me. 

THANKS FOR ALL KIND OF PROPOSALS and comments

**Comment by brianstock** [comment]
I think you can just include "Individual" plant/"consumer"/"mix" as a factor (either fixed or random effect as you wish, probably random effect since you are more interested in the overall source proportioning). Then you have source data by factor as in the wolves example: Include a column for "Individual" in the source data file and set `source_factors="Individual"` when reading it in.

Unfortunately MixSIAR is only set up to treat source factors as fixed effects (i.e. independently, not sharing information across individuals)... It'd probably be better in your case to have "Individual" as a random effect when fitting the source data. You could fork MixSIAR and modify your own version to do this.
