### ISSUE TITLE
the number of samples affects the result of a single sample

### ISSUE THREAD

**Issue by ddd212** [brianstock/MixSIAR#221]
Hello，
I have a dataset of more than 500 samples (19 differnt sites). However, when I run the models of mixsiar with default priors (alpha.prior=1; resid_err <- FALSE, process_err <- TRUE for individual; TRUE and FALSE for site factor), 4 sources and 3 iso_names, some problems occur:
1.the number of samples affects the result of individual sample. For example, when i run the model with one sample (Sample I), the proportion is 0.45 from source A. when i run it with 10 samples, the profortion of Sample I becomces 0.46. 30 samples, it becomes 0.47; 50----0.44; 100----0.39; 200---0.24; 300----0.28; 400----0.14; 500----0.24........I don't know why?
2.when i run the model with individual samples of 19 sites, and then average the results at every site; while i run the model with site as factor, the results are very different from individual model......I also dont know why? The same issue was at https://github.com/brianstock/MixSIAR/issues/209.
Thanks for your help!

**Comment by brianstock** [comment]
I'm not exactly sure without more information. But:
  1. Make sure the models are all converged.
  2. In principle, I would expect the results to change because you're adding more data to pull the model estimate away from the prior. If you increase the sample size (leaving the data the same, for instance by duplication = "data cloning"), you should see this. Your results are not gradually moving away from the prior and converging on a result, so I'm guessing you are not simply replicating the same datapoint?

If you are interested in proportions by Site, I would not run the model on individual samples and then average by Site. Better to run one model with Site as a fixed/random effect, then you use all of your data to inform the site proportions and avoid estimating lots of extra error terms.

**Comment by ddd212** [comment]
thank you
