### ISSUE TITLE
accessing the output to get objects

### ISSUE THREAD

**Issue by jrfrun** [brianstock/MixSIAR#229]
I am trying to get access to the ouput of mixsiar. My understanding is that the output goes to jags.1 but when I try the command below, it does not recognize the jags.1 object after I run the model

> df <- jags.1$BUGSoutput$sims.matrix
Error: object 'jags.1' not found

**Comment by brianstock** [comment]
There is not enough information to help. Please post a [minimal working example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example).

**Comment by jrfrun** [comment]
I was trying to construct boxplots for the posterior proportions, so I am trying to get access to those number which are provided as a text file in the output, but want to work within the program and not sure how to get their values without having to type them in from the summary.txt file

**Comment by brianstock** [comment]
If `jags.1` doesn't exist, it's either because

1. You haven't saved a model to that object, as in `jags.1 <- run_model(run="normal", mix, source, discr, model_filename)`
2. You're using the GUI, in which case the `jags.1` object is stored in the `mixsiar` environment and you need to call `mixsiar$jags.1`. See manual section 3.1.13.

The MCMC chains are in the `jags.1$BUGSoutput$sims.list` object. See examples in the manual and new vignette [Modify output](http://brianstock.github.io/MixSIAR/articles/modify_output.html).
