### ISSUE TITLE
analysis of amino acids

### ISSUE THREAD

**Issue by jrfrun** [brianstock/MixSIAR#236]
HI Brian
While this is not about an issue, I was wondering if you could guide me to some example on how to carry out analysis using the mixsiar package for analysis of amino acids

**Comment by brianstock** [comment]
Sorry this was so slow... Two of the MixSIAR example datasets use fatty acid profile data: Isopod and Cladocera. 

Read the Source Data section of [Article S1](https://peerj.com/articles/5096/#supp-1), advice is to treat source data as mean+SD to avoid assuming source data are normally distributed. Assuming that the source *means* are normally distributed is fine due to the Central Limit Theorem. Assuming that the mixture data are normally distributed is addressed in Article S2.

Alternatively, check out [fastinR](https://github.com/Philipp-Neubauer/fastinR), which was designed specifically to handle compositional tracer data.
