### ISSUE TITLE
Multimodal Posterior Distributions

### ISSUE THREAD

**Issue by GideonvdB** [brianstock/MixSIAR#238]
Hi Brian, 

I've generated a mixing modal to try and assess potential differences in the diet composition of predators sampled in 2 different decades (thus decade = fixed effect). 

The model was run with 7 sources, using the 'extreme length' specification, with a process x residual error structure.
The model has converged well (both Gelman and Geweke stats look good). 

However, the posterior density for the predators in one of the decades ("Model 1 2015 - 2019" in the figures) is clearly multimodal. 

I'm not sure how to proceed with the interpretation of this.
Is it common for mixing models to produce posterior densities such as these? 
Are there perhaps further steps that can be taken to try and iron this out? 

Attached is the Posterior Densities for both decades, as well as the 25, 75 and 95% Bayesian credibility intervals (created with siberDensityPlot) for both decades. 

Any help with this would be great. 
Cheers

![Posterior density](https://user-images.githubusercontent.com/68074649/87067944-22abaf00-c215-11ea-8d65-3a93e0faf5c5.png)
![Bayes credibility](https://user-images.githubusercontent.com/68074649/87067958-293a2680-c215-11ea-8e15-83da2ef9df15.png)

**Comment by brianstock** [comment]
Yes, it looks like in the recent decade the model oscillates between "all gold" and "green/orange". How many tracers do you have? What does the mixing space (after correcting for TDF) look like - is there clear confounding of sources?

No, it's not uncommon. That's why looking at the full posteriors is important. And an advantage of fitting the model with MCMC instead of maximum likelihood (where bimodality would be hidden). I don't think there's anything wrong with showing your results and discussing them appropriately. You could make a ternary plot (ala [Fig 2. in Semmens et al. 2009](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0006187#pone-0006187-g002)) with gold/green/orange that would clearly show it's either "all gold" or "green/orange". 

Things you can try:
  - If you have auxiliary data, you could use an informative prior (see killer whale and mantis shrimp examples)
  - Reduce the # of sources (either a priori based on biology or a posteriori)

**Comment by GideonvdB** [comment]
Hi Brian, 

Thanks for that incredibly quick response! 

We are working with 2 tracers. 
And here is what our isospace looks like. 

![Model3 isospace](https://user-images.githubusercontent.com/68074649/87124139-77d4d880-c288-11ea-867b-4a06e64dfeb0.png)

Unfortunately there isn't much auxiliary data to be used to inform the priors. However, I will discuss this with my co-authors and may get back to you on this.

**Comment by brianstock** [comment]
Feel free to re-open this in the future... but for now I'm going to close it.
