### ISSUE TITLE
Scaled  posterior distributions

### ISSUE THREAD

**Issue by VirginiaMorera** [brianstock/MixSIAR#24]
Hi, this is more of an open question than an issue, and I am not sure if this is the right place to post it, so please feel free to redirect me somewhere else if it is not. 

I have come to realize that in the posterior distributions plot, the density of all sources is scaled to 1. As an example, my model's output from MixSIAR looks like this
![scaled](https://cloud.githubusercontent.com/assets/11058769/6749702/e45913b6-cef2-11e4-8003-6156fab5e25d.JPG)
but if I extract the posteriors from the jags output and plot them, without scaling the y axis, they look like this. 
![test_histograms](https://cloud.githubusercontent.com/assets/11058769/6749680/b37f1574-cef2-11e4-8117-6d2f73ec4264.png)

I was wondering, looking at the non-scaled plot, 
a) if I can say with the same confidence that my consumers are feeding from marine and freshwater sources as I can say they are NOT feeding on terrestrial or refuse sources. 

and b) if the distributions with lower densities are not to be trusted, whether there's something in the output (in the summary or diagnostics file, for instance) to indicate it.

**Comment by eric-ward** [comment]
Yes, the scaled plot is the default because in some cases it may be tricky to see all the proportions (your data is a good example of this). There's no automatic way to completely rule out sources, but presenting the median values, or credible intervals could be one way to go. The refuse CIs will of course be higher, and whether that constitutes whether or not your consumers are eating that diet depends on your threshold. Or you could use the posteriors to generate 1-sided probability statements, e.g. "The probability of Terrestrial being more than 1% of the diet is XX"

**Comment by brianstock** [comment]
Hi Virginia,

Thank you for asking this question and providing a clear example - I've answered this by email several times!

See [Interpreting posterior density](https://github.com/brianstock/MixSIAR/issues/21):
>The y-axis units are pretty much meaningless in both scaled and unscaled plots. I scaled the posterior densities because in some situations the y-axis would be very high for one source (ex. when one source is known to be close to 0, the y-axis can be very high), and you couldn't see the other sources well. The scaled posterior densities are no longer true probability distributions, because they don't integrate to 1. But visually they are the same, in that 95% of the area under the curve shows you 95% probability.

**Comment by VirginiaMorera** [comment]
Oops, sorry I didn't realise this had been answered before. Thank you very much, that was really helpful!
