### ISSUE TITLE
Appropriate TEFs and MixSIAR

### ISSUE THREAD

**Issue by CurrentDrMario** [brianstock/MixSIAR#262]
Hello,

I have a question about how MixSIAR uses TEFs. My understanding is that the TEF selected for MixSIAR must account for the number of trophic steps between source and consumer. If there is one step separating the source and consumer, then the TEF could be used as normal (let's say 3.4 for N and 0.4 for C). However, if there are two trophic steps separating the source and consumer, then these need to be adjusted (3.4 x 2 = 6.8 for N and 0.4 x 2 = 0.8 for C) in order for the model to resolve correctly. Assuming all consumers fit within source polygons, is this a valid approach for TEFs in MixSIAR?

I ask because I've been informed that MixSIAR allows for the use of a single-step TEF in situations involving two trophic steps (e.g. using 3.4 for N and 0.4 for C when my consumer is two steps from the source). I'm not aware of MixSIAR making any adjustments for this and the consumers for my data fall outside of the source polygon with this approach. That said, I could be wrong and that's why I'm posting here.

Any input is appreciated!

**Comment by Don-Phillips** [comment]
Conceptually I think this is correct that you could multiply the TEFs by the number of trophic level difference, but I don't think MixSIAR will do that for you. Here's a piece about that from our "best practices" paper (Phillips et al. 2014, Canadian Journal of Zoology 92: 823-835):

- Whereas most studies focus on the dietary contributions of prey
- items directly consumed, some studies aim instead to measure
- the importance to the consumer of food webs based on different
- basal resources (generally producers or detritus). One example of
- this is the study of Reid et al. (2008) on the importance of biofilm,
- allochthonous detritus, macrophytes, and algae basal resources
- for stream consumers. This requires additional information about
- trophic structure, as the DTDFs must be multiplied by the number
- of trophic levels between the consumer and the basal resources to
- appropriately correct the isotope values used in the mixing model
- analyses.

This works, if for example, all the sources considered are ultimate basal resources such as in the Reid paper, and you're trying to separate out their influences rather than that of each proximate prey species. I think there are several problems with this in practice, though. One is how to estimate those trophic level differences. There could be many possible intermediate paths (of different lengths) between the basal resource and your consumer of interest. Also, if you include some of these proximate prey species as sources along with basal resources, things can get confounded. Each of those species is based on consumption of some basal resource through some trophic chain, and so you would be in a sense double-counting that basal resource. I think it would be best to try and stick with just basal resources, corrected by the appropriate trophic level TEF multiples, or stick just with prey species directly consumed with just the single-level TEFs. Just my two cents.

**Comment by brianstock** [comment]
Hi Mario,

You're correct, MixSIAR estimates one trophic step and will use whatever TDF values you supply. If you are estimating source proportions to a consumer 2 trophic steps removed, yes you need to use an appropriate TDF for 2 trophic steps. I'd imagine you should also increase the TDF uncertainty. By how much I do not know, but there is bound to be substantial uncertainty with 2 trophic steps unless you've done a diet experiment to inform the TDF values.

Note that this does not have to be the same for all sources either. The [palmyra example](https://github.com/brianstock/MixSIAR/blob/master/inst/extdata/palmyra_discrimination.csv) from [McCauley et al. 2013](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/11-1653.1) uses TDF = 0 for two sources and non-zero for the third.

**Comment by CurrentDrMario** [comment]
@brianstock and @Don-Phillips,

Thank you both for clearing this up for me. Your responses were enormously helpful!

Best,
Mario
