### ISSUE TITLE
mix data not falling within mixing space/polygon

### ISSUE THREAD

**Issue by eapollardd** [brianstock/MixSIAR#272]
Hi Brian,

I am having issues with a few things, mainly my mix data not falling within my mixing polygon. I am determining lobster diet with 2 size classes (fixed) with several prey sources such as gastropods and urchins. My TDF is borrowed from a study on a congener species, and it should be accurate. With my output I am running into 2 issues my data is not in space and then all of my convergence diagnostics indicate a non-converged model. I am currently running the model on "normal". Is there a solution other than finding a new TDF? I've posted two different isospace plots and diagnostics 
for two different sites.

Any help is greatly appreciated!

Erica

[isospace_plot_ANA_SW_1_2.pdf](https://github.com/brianstock/MixSIAR/files/6159944/isospace_plot_ANA_SW_1_2.pdf)
[diagnostics.txt](https://github.com/brianstock/MixSIAR/files/6159950/diagnostics.txt)
[isospace_plot_CRUZ_1_2.pdf](https://github.com/brianstock/MixSIAR/files/6159958/isospace_plot_CRUZ_1_2.pdf)
[diagnostics_CRUZ.txt](https://github.com/brianstock/MixSIAR/files/6159964/diagnostics_CRUZ.txt)

**Comment by brianstock** [comment]
If your consumer data don't fall in the mixing polygon, I would not run a mixing model because the assumptions are clearly not met. Your case is not that bad though. Also note that whenever you read that the consumer data must fall in the source polygon, it's really the *mean* of the consumer data that is fit in the model.

For ANA, the consumer data are clearly in the polygon. But the geometry is tough - the sources lie on a line such that MEG, STR, and MESO are confounded. This is similar to the [killer whale ex](http://brianstock.github.io/MixSIAR/articles/killerwhale_ex.html). Option 1: incorporate other information (e.g. stomach contents in the killer whale ex) in the model as an informative prior. Option 2: combine MEG, STR, and MESO after running the model. You'll end up with percent CONE vs. not-CONE, which may answer your scientific question (or not). The diagnostics on CONE vs. not-CONE should look a lot better.

For CRUZ, there is large uncertainty in d15N for the TEG source, and the model should be able to effectively say it's more likely that TEG d15N is ~16. The consumer data then lie on a line between TEG and MEG. 

I would be careful asserting that the TDF is borrowed from another species and "should be accurate".

Best,
Brian

**Comment by AVGPR** [comment]
Hi Brian and Erica, 

If I can intrude here with a "related" issue... 

I've been using MixSIAR to identify tree water sources (2H and 18O), but the problem is that no matter the dataset, the sources always fall along a line (like in Erica's ANA plot). So the convex hull area is always really small, although the consumer (tree) more or less falls along that line as well. I've been wondering for a while if in this sense, is it really appropriate to use MixSIAR for plant water sources? 

And regarding the Option 2 you suggested here of combining those bottom sources so that you end up with two sources instead. I have tried this with all my plant data sets but then the correlation plots show a full -1.00 correlation, and no matter what, the posterior distributions for each source are a mirror of each other... I guess it makes sense but I wonder if I can trust those results? In my case I have always decided to go with either 3 or even 4 sources, because after many trial and error attempts, it seems that 3 or 4 are the best for this case where the sources fall along a line. It has helped with convergence and with the amount of model run time. In one case, I found 5 sources was also good, but ended up aggregating into 3 anyway.

Best, 
Adriana

**Comment by brianstock-NOAA** [comment]
To clarify: It's not MixSIAR specifically, you'll get the same result with any mixing model. I don't think "appropriate" or not is the right way to think about it. It's not inappropriate to use MixSIAR if the convex hull area is small, it just means the stable isotope data are not very informative about the proportions and the credible intervals will be very wide.

Yes, that is expected. In a 2-source model, p1 + p2 = 1 so they will be 100% correlated. Why would you not trust those results? FWIW, it worked out in this mantis shrimp diet analysis ([deVries et al. 2016](https://link.springer.com/article/10.1007/s00442-016-3667-5)) to aggregate 6 sources into 2, because the scientific question was more about the 2 aggregated prey groupings. See [Figure 4](https://link.springer.com/article/10.1007/s00442-016-3667-5/figures/4), where the aggregated priors and posteriors are mirror images of each other.

**Comment by AVGPR** [comment]
Hi Brian, 

Thank you very much for your answer. Sorry, "not trusting" the results is not really what I meant, more like how to best interpret results when they are so correlated. Maybe I don't understand it fully, but I was confused because I thought two sources being so highly correlated would cause problems, and that in some cases (with more than 2 sources of course) it was recommended to aggregate such highly correlated sources. But then if this is expected in a 2-source model, then it's ok and guess I hadn't understood it entirely.

Thanks for the reference, I see it has discussion on the correlations of sources, so I'll read through, thanks.

Thank you, 
Adriana

**Comment by brianstock-NOAA** [comment]
Yeah, it's not a problem because a 2-source mixing model only estimates the proportion of one source (p1) and then calculates the other from the sum to 1 restriction (p2 = 1 - p1). 100% correlation is guaranteed. With more sources some negative correlation is still expected for this same reason, i.e. the sum to 1 constraint.

In general, correlation between the estimated proportions is just something to be aware of. It is not uncommon for there to be multiple plausible proportion vectors, which you'd see as multimodal posteriors. In that case, there is typically strong negative correlation between the dominant sources - the solution is either one p vector or the other. A mixing model with this result is perfectly valid, just inconclusive.

**Comment by AVGPR** [comment]
Hi Brian, 

Thank very much for your help, it actually clarifies a lot of things for me. Precisely I just ran a model where two sources had bimodal posteriors and yes, the sources were strongly negatively correlated. So I also did some more quick reading of papers which discuss bimodal or multimodal posteriors which also helped understand better.

Thanks so much, 
Adriana
