### ISSUE TITLE
MixSIAR 2.1-2.2 is not creating Isospace or Processing Output on OSX Yosemite

### ISSUE THREAD

**Issue by reaperofchaos** [brianstock/MixSIAR#28]
I am having some problems running MixSIAR 2.1-2.2 in RStudio using a Mac running OS X Yosemite. I have managed to get the MixSIAR Gui to run, but I am finding that I am unable to generate an isospace or process the output. I have received a number of different errors but they all appear to be related to plotting functions. For example when I run the Wolves example described in the MixSIAR Gui manual, I receive the following error after clicking Make isospace plot. 

```
Error: Incompatible lengths for set aesthetics: size, linetype 
```
Then after running the model, which appears to run and clicking Process output I receive the error. 
```
Error in print(xyplot(as.mcmc(p.global), strip = strip.custom(factor.levels = source_names))) : 
  could not find function "xyplot"
```

**Comment by brianstock** [comment]
Hi Jacob,

Thanks for reporting the bug... I'm getting the same error with the `xyplot` in the output section as well now. I believe it's fixed by specifying that the `xyplot` function comes from the `lattice` package.  If you want to fix your version of the code before I get to it, replace all instances of
```
xyplot(
```
with
```
lattice::xyplot(
```

**Comment by brianstock** [comment]
In addition to the above change, also necessary to add
```
require(lattice)
```
to the top of "mixsiar_script.r" and "mixsiar_gui.r". Done now.
