### ISSUE TITLE
Comparing models when some covariates have NAs

### ISSUE THREAD

**Issue by Mari1nature** [brianstock/MixSIAR#353]
Hello.
I would like to know if it is possible to compare 3 models in MixSIAR from the same mixture set, but with one of the covariates (used in one of the models) having some NAs.
Thanks in advance,
Mariana

**Comment by AndrewLJackson** [comment]
Hi marian

If I understand correctly, the answer depends. You can compare models using DIC or other such model performance metrics so long as the response variable data is identical – in MixSIAR models this would be the mixture data.

NA values can occur the response variable (or indeed any variable that are assumed to come from a distribution) and in such cases the missing value will be inherently imputed by the algorithm. This is a really nice feature of fitting models using JAGS (as MixSIAR does).

NA values in a simple linear covariate are a problem however, since they are simply multiplied or added in the model structure and so will propagate NA values all the way through the model.

The problem you will face is similar to missing values in a standard glm() type model. Either you or the fitting algorithm will end up deleting the entire row where a missing value exists, and so the response variable data will change, rendering comparisons between models using AIC or DIC impossible.

To summarise:

NA values I the response variable (the mixtures) are fine.

NA values in the source data are (should be) fine, so long as you are supplying the raw data and letting MixSIAR estimate the means and standard deviations.

NA values in a TDF / TEF are not ok.

NA values in the corrections are not ok.

NA values in a linear or categorical covariate are not ok.

Hopefully im correct in all this and that’s helpful

Best wishes
Andrew

From: Mari1nature ***@***.***>
Date: Tuesday, 8 August 2023 at 15:42
To: brianstock/MixSIAR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [brianstock/MixSIAR] Comparing models when some covariates have NAs (Issue #353)

Hello.
I would like to know if it is possible to compare 3 models in MixSIAR from the same mixture set, but with one of the covariates (used in one of the models) having some NAs.
Thanks in advance,
Mariana

**Comment by Mari1nature** [comment]
Hello Andrew,

Thank you for your reply, it was very helpful indeed. 

Best wishes,
Mariana
