### ISSUE TITLE
Fixed and random effects

### ISSUE THREAD

**Issue by andrewcparnell** [brianstock/MixSIAR#36]
Hi Brian,

I'm helping someone run a script and I can't get it to run a model where they have both a random effect and a fixed effect. In the `load_mix_data' function it seems to be calculating a value for the total number of effects and then looping through these which means that it's looking for e.g. the second fixed effect in the mix data which only has one fixed effect.

Drop me a line if that's unclear.

Andrew

**Comment by brianstock** [comment]
Thanks for the heads up, I'll take a look.

**Comment by brianstock** [comment]
Should be fixed in the new version I tagged for release (3.0). In the new manual I don't have an example with mixed effects, but you can easily see that it works now by changing  `fac_random` in the Wolves Example at line 51 (`load_mix_data`).

Original model (Region and Pack both random effects):
```
fac_random=c(TRUE,TRUE)
```
Mixed effect model (Region = fixed effect, Pack = random effect):
```
fac_random=c(FALSE,TRUE)
```
