### ISSUE TITLE
DIC model selection and individual variation

### ISSUE THREAD

**Issue by AdamDuBour** [brianstock/MixSIAR#41]
A  few questions for anyone that might have some insight. 
I am interested in partitioning the variation of the population niche by sub-groups and individuals. When I include the group covariate and individual as random effects the median value for groupSD=1.04 and indSD=0.48 indicating that the majority of the variation in the population niche is attributable to the group effect as demonstrated in the wolf example from the user manual. 

  However, does the relative lack of support for a model, indicated by higher DIC value, that includes individual and group as random effects (Model 1) compared to a model with only the group covariate (Model 2) preclude me from making such an inference?  Does this indicate that indeed individual variation is minimal and I can still make the inference that the population variation is driven by the group effect despite the model is not the "best fit" to the data? Both models have converged by the way.

 Can I still make the inference regarding the relative level of variation between group and individual from Model 1 and then use Model 2 when making specific inferences for population and group diet estimates? Can I make any inference on niche variation when including only group as a random effect?

   Any thoughts or comments would be appreciated
-Adam DuBour

**Comment by brianstock** [comment]
Hi Adam,

What is the difference in DIC between the two models?  Generally, only differences in the 3-7 range are considered significant (p.613 Spiegelhalter et al. 2002, http://onlinelibrary.wiley.com/doi/10.1111/1467-9868.00353/pdf).

Generally, you don't need to worry so much about saying one model is correct and the other is wrong (and therefore can't make inferences from the "wrong" model).  Quoting Hooten and Hobbs (2015, http://www.esajournals.org/doi/pdf/10.1890/14-0661.1), "DIC can be used for ranking models and finding those that should predict better than others."  In other words, it's not that the model with higher DIC is wrong, it's just not expected to predict as well as the model with lower DIC.  This is the same motivation for model weighting/averaging instead of choosing one "correct" model (e.g. Burnham and Anderson 2002).

In your case of diet varying by groups and individuals, the model with group and individual is not incorrect... unless you do think that all individuals have the exact same diet.  DIC is telling you that estimating the extra parameters for individual diet variation is probably overfitting your data, and your predictions of future data would be better by only estimating the group diet variation.  So yes, I think you can report results from both models, using Model 1 to infer that variation between groups is more important than variation of individuals within groups, and then using Model 2 to provide diet estimates.

-Brian

**Comment by brianstock** [comment]
Also, sorry for taking so long on your previous question on the implementation of a mixed model (fixed and random effects), https://github.com/brianstock/MixSIAR/issues/22!  It has been noted by several others now, https://github.com/brianstock/MixSIAR/issues/36 and https://github.com/brianstock/MixSIAR/issues/38.

**Comment by AdamDuBour** [comment]
Brian,
  Thanks for the reply. Well, the difference in DIC between the two models is relatively large, at about 12. According to Speigelhalter et al. (2002) this difference would mean Model 1 "deserves considerably less support". However, if I understand you correctly I should still be able to make the inferences as discussed above. 
   No worries on the mixed model issue. I've been following those threads and I've decided to set the issue aside for the time being. 
   -Adam
.
