### ISSUE TITLE
Problems loading data

### ISSUE THREAD

**Issue by SharonEv** [brianstock/MixSIAR#48]
I have just loaded GUI MixSIAR on my Mac OSX 10.11.1, R 3.2.2 fire Safety and started to practise with the wolves sample data and got warnings at the end of this message (although Brian answered in an email that he also gets warnings). 

I carried on at first as I was able to load some of the data i.e. the Discrimination data but not the source data (a blank box) and the mixture data appeared to work but no tick - however when I went back through it to check if I did everything correctly I saw that I didn't get the option box to tick  nested/hierarchical.  

I  tried 
> mixsiar$mix
NULL

Thanks in advance for your help! 

(R:1199): Gtk-WARNING **: Attempting to set the permissions of `/Users/sharonevery1/.local/share/recently-used.xbel', but failed: No such file or directory
Error in if (n.re == 2 & fac_nested[2]) { : 
  missing value where TRUE/FALSE needed
Error in if (n.effects > 0) { : argument is of length zero

(R:1199): Gtk-WARNING **: Attempting to store changes into `/Users/XXX/.local/share/recently-used.xbel', but failed: Failed to create file '/Users/1/.local/share/recently-used.xbel.MS137X': No such file or directory

(R:1199): Gtk-WARNING **: Attempting to set the permissions of `/Users/xxx1/.local/share/recently-used.xbel', but failed: No such file or directory
Error in if (n.effects > 0) { : argument is of length zero the warning below

**Comment by kristingleeson** [comment]
I'd like to know is there is a solution to this issue as well. I had this happen to me on the mac - exactly the same. I decided to use my windows machine instead and I'm still getting the same, first part of this issue, where no pop up box appears to ask about nested/hierarchical and my error is the following:

Error in if (n.re == 2 & fac_nested[2]) { : 
missing value where TRUE/FALSE needed
Error in if (n.effects > 0) { : argument is of length zero

It allows me to load the mixture data before this error appears, then I can't continue on because the load source data pop up box is blank.

Help would be appreciated! Thanks :)

**Comment by brianstock** [comment]
Hi @SharonEv  and @kristingleeson,

Sorry for the slow response, I've been travelling the past 2 weeks.  I believe this is fixed now - try the latest version I just uploaded (https://github.com/brianstock/MixSIAR/releases/tag/3.0.2).

Thank you for reporting this issue!  I'll wait to close it until I hear from you that it's working.

-Brian

**Comment by SharonEv** [comment]
Hi Brian,
             Have just finished the wolves example and everything loaded correctly and now just waiting for the normal MCMC model to run through but looks like everything is working! Now for my data.... 
Thanks for doing this! 
Sharon
