### ISSUE TITLE
Option to Suppress Scaled Posterior Density Plots for Random Effect Levels

### ISSUE THREAD

**Issue by JasonMHill** [brianstock/MixSIAR#49]
I am working with a large bird dataset with multiple measurements from the same individual (i.e., multiple feather samples were collected from the same individual). I am treating the individual bird as a random effect. When I process the output, MixSIAR attempts to create a scaled posterior density plot for every individual bird (i.e., every level of my random effect). I generally like this behavior, except in this case:

1) I have over 100 individual birds and R won't open that many plotting windows, so I see the first 60 plots and then R throws up a "too many windows open" error. I would like the ability to suppress these plots for the random effect. Unchecking all of the "save plots as" boxes has no effect.

2) [more importantly] The "too many open devices" error prevents the model summary statistics and diagnostics from being printed to the screen and it prevents the creation of the .txt summary file. I know that I can manually create this summary file from the BUGS output. 

In lieu of adding the "suppress scaled posterior density plots" feature, perhaps just tweaking the code so that the command to write and print out the summary/diagnostic statistics comes before the command to print out the scaled posterior density plots.

**Comment by brianstock** [comment]
Hi Jason,

Sounds like a cool dataset!

I actually already had this as an option in previous MixSIAR versions, but removed it because the GUI was getting cluttered as I added the plot your prior feature.  I think I'll leave the GUI as is, but you can easily change this `sup_post` behavior in your personal copy by replacing `FALSE` with `TRUE` on:
  - line 152 of `mixsiar_script.r`
  - line 329 of `mixsiar_gui.r`

That's a good suggestion to write and print summary stats and diagnostics before the plots... but since I've already coded the suppress posterior plots option, I think I'll leave it as is for now.

Thanks,
Brian

**Comment by JasonMHill** [comment]
Excellent,
Thanks for the tip Brian.
Jason


On Mon, Dec 14, 2015 at 7:53 PM, Brian Stock <notifications@github.com>
wrote:

> Closed #49 <https://github.com/brianstock/MixSIAR/issues/49>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianstock/MixSIAR/issues/49#event-491682769>.
>



-- 
Jason M. Hill, PhD
Post-doctoral Researcher
Vermont Center for Ecostudies
802.649.1431 Ext. 112
http://vtecostudies.org/about-us/staff/jason-hill/
Latest blog post here
<http://www.wildlifemanagementinstitute.org/index.php?option=com_content&view=article&id=840:cru-corner-estimating-effect-of-landscape-changes-from-marcellus-natural-gas-development&catid=34:ONB%20Articles&Itemid=54>
