### ISSUE TITLE
Problem with reading data

### ISSUE THREAD

**Issue by SharonEv** [brianstock/MixSIAR#50]
Hi!  

         I am trying to put my data in to MixSIAR and I can manage to get the priors graph to be produced but when I try and get the model to run I get an error message: 

Error in jags.model(model.file, data = data, inits = init.values, n.chains = n.chains,  : 
  RUNTIME ERROR:
Compilation error on line 139.
Unknown variable frac_sig2
Either supply values for this variable with the data
or define it  on the left hand side of a relation.

 I am assuming its an error with the data file but I am not quite sure what.I have tried the wolves, geese and the Clacoderan sample data and they all worked. I have 19 Fatty acids, and 4 species with 6 prey that I am entering raw and no discrimination factors. What should I be seeing in the data to make these errors? 

When I first started getting these errors I had included dC and dN with the model  which I do have discrimination factors and concentration amounts. But I thought this might have created the errors as I didn't have values for the fatty acid discrimination factors or concentration - If  I'd put 0 I presume the model would not be accounting for the error of not knowing the value. Would it work to put NAs instead? In fact can NA be used anywhere in the data?

**Comment by brianstock** [comment]
Hi Sharon,

Yes, you're right---an error in `frac_sig2` means there is likely a problem with the discrimination file.  When using the "Means + SDs" option, all of the tracer labels you select when loading the mix data must appear in the source and discrimination files with "Mean" and "SD" appended before.  E.g. "d13C" in mix file becomes "Meand13C" and "SDd13C" in source/discrimination files.  With fatty acids this is a pain since you have 19 tracers and discrimination is 0.  The cladocera example should be helpful, look at `cladocera_discrimination.csv`.

NAs not allowed, use 0.  The model will account for the uncertainty in discrimination values using the values you use for discrimination SD - if you set SD = 0 that means you know discrimination factors exactly.

Hope that helps...

-Brian

**Comment by SharonEv** [comment]
Thanks Brian, yes that did help. However the only way I could get the Fatty acid data to work was to determine the mean and SD on the spreadsheet first. As when I added the data raw it come up with an error message saying that it was positive matrix (apologies I can't remember the message exactly).
Thanks again
Sharon

**Comment by Blanestela** [comment]
Hi 
 I am trying to put my data in to MixSIAR but I have the problem with source data and with Discrimination data, I try to solve but I could not.

Error in load_source_data(mixsiar$source_filename, source_random_effects,  : 
  *** Error: Source mean column names mislabeled.
    Should be 'Mean' + iso_names from mix data file, e.g. 'Meand13C' if
    mix$iso_names = 'd13C'. Please ensure headings in source data file match
    this format and try again. Alternatively, if you have raw source data,
    you should set data_type='raw'.
Error in load_discr_data(mixsiar$discr_filename, mixsiar$mix) : 
  *** Error: Discrimination mean column names mislabeled.
    Should be 'Mean' + iso_names from mix data file, e.g. 'Meand13C' if
    mix$iso_names = 'd13C'. Please ensure headings in discr data file match
    this format and try again.
> This is my data

,Meand13C,SDd13C,Meand15N,SDd15N,n
CAM,-16.12,0.14,14.53,0.8,5
CEF,-16.92,1.31,13.56,3.35,9
EUF,-16.91,0.63,11.78,1.54,5
MESOP,-17.12,0.6,15.42,1.69,20
MYC,-17.37,1.04,14.24,3.14,20

**Comment by marcelomw** [comment]
Hi,

I have the same problem of Blanestela.
I am trying solutions, but still not working. Someone else have had this problem?

**Comment by dinizreis** [comment]
I guess maybe it is because I shoud not put the sample number in the discrimination file, just put it in the source one.

Although, I still have a similar problem.
Error in jags.model(model.file, data = data, inits = init.values, n.chains = n.chains, :
RUNTIME ERROR:
Unable to resolve the following parameters:
Sigma.ind[1,1:2,1:2] (line 113)
Sigma.ind[2,1:2,1:2] (line 113)
Sigma.ind[3,1:2,1:2] (line 113)
Sigma.ind[4,1:2,1:2] (line 113)
Sigma.ind[5,1:2,1:2] (line 113)
Sigma.ind[6,1:2,1:2] (line 113)
conc[8,1] (line 83)
conc[8,2] (line 83)
mix.mu[1:2,1] (line 113)
mix.mu[1:2,2] (line 113)
mix.mu[1:2,3] (line 113)
mix.mu[1:2,4] (line 113)
mix.mu[1:2,5] (line 113)
mix.mu[1:2,6] (line 113)
n_array[8] (line 14, 15, 16)
Either supply values for these nodes with the data
or define them on the left hand side of a relation.

Could anyone help me?

Thanks

**Comment by leedrake5** [comment]
I've got the same problem as others have mentioned here. 

> Error in jags.model(model.file, data = data, inits = init.values, n.chains = n.chains,  : 
>   RUNTIME ERROR:
> Compilation error on line 89.
> Unknown variable I
> Either supply values for this variable with the data
> or define it  on the left hand side of a relation.

In addition, I made minor modifications to load_mix_data and load_source_data so that they could read R objects, not just CSV files (pulling from a database that needs to run in a shiny app). Any chance I can submit those changes to MixSIAR, and how?

**Comment by MaartenWynants** [comment]
After some trial and error I think I have fixed this issue. 
This error only occurs if you only use 1 error class (either residual or process error only). 
For example in my case : 
model_filename <- "MixSIAR_model.txt"   
process_err <- FALSE
resid_err <- TRUE
write_JAGS_model(model_filename, **process_err, resid_err**, mix, source)

jags.1 <- run_model(run="test",mix,source,discr,model_filename, alpha.prior = alpha, **process_err,resid_err**)

Make sure in your code these are in the same order: 1. process and 2. residual 

Hope that helps
