### ISSUE TITLE
Combine sources a posteriori

### ISSUE THREAD

**Issue by akbreezo** [brianstock/MixSIAR#53]
Is there a way to combine sources a posteriori following "Process output"? I'd like to explore this option rather than a priori combination.

**Comment by brianstock** [comment]
Yes, you can combine sources a posteriori with the model output.  I haven't written a function to do this specifically, but you can access the output (see https://github.com/brianstock/MixSIAR/issues/30) and do it manually.

Make sure to add each draw from the source chains, then calculate summary statistics.... instead of just adding the summary statistics from the sources you want to group.

I've done this for a separate analysis (full code at https://github.com/brianstock/mantis_shrimp_diet/blob/master/Fig4_prior_posteriors_uninf.r).  We had 6 prey sources and lumped them into 2 groups of 3 (hard-shelled vs. soft-bodied):

```R
setwd("/home/brian/Documents/Isotopes/mantis_shrimp_diet/15_uninf_prior")
load("finished.RData")
library(R2jags)
attach.jags(jags.1)
# post.grass aggregates the 6 prey sources into 2 groups, hard vs. soft 
post.grass <- data.frame(hard = p.fac1[,1,3]+p.fac1[,1,4]+p.fac1[,1,6], soft = p.fac1[,1,1]+p.fac1[,1,2]+p.fac1[,1,5])

# Get median +/- 95% CI proportions for hard vs. soft
print_CI <- function(vec){
	med <- median(vec)
	low <- quantile(vec,.025)
	high <- quantile(vec,.975)
	return(round(c(med,low,high),3))
}
apply(post.grass,2,print_CI)

# You could also plot the aggregated posteriors:
post.grass.df <- post.grass %>% gather(variable,value,1:2)
post.grass.plot <- ggplot(data=post.grass.df, aes(x=value, fill=as.factor(variable), colour=as.factor(variable))) +
					geom_density(alpha=.3) +
					# guides(fill=FALSE,colour=FALSE) +
					theme_bw() +
					xlab("Diet proportion") +
				    ylab("Posterior density") +
				    coord_cartesian(xlim = c(0,1)) +
				    labs(title = "Aggregated posterior density: Seagrass") +
				    theme(legend.position="none")
```
