### ISSUE TITLE
Interaction continuous-categorical variable

### ISSUE THREAD

**Issue by MARM09** [brianstock/MixSIAR#97]
Hi!
Is it possible to test an interaction between a categorical and a continuous variable using MIXSIAR?

Thank you,

Miguel

**Comment by brianstock** [comment]
Hi Miguel,

Yes it is - assuming you have enough data and all sources are present for all levels of your categorical variable.  For clarity, let's say you have isotope/FA data for bears of 2 sexes (M, F) and you have the weight of each bear.  Sex = continuous, Region = categorical.  You'll have to run separate models for each region. Using the current code, the workflow would go something like:

1. split your mix/consumer (bear) data into separate files, one for each sex (e.g. mix_M.csv, mix_F.csv)
2. copy/split your source data into separate files (source_1.csv, etc.)
3. when loading mix data, specify the same continuous effect:
`mix.M <- load_mix_data(mix_M.csv, factors=NULL, cont_effects="weight")`
`mix.F <- load_mix_data(mix_F.csv, factors=NULL, cont_effects="weight")`
4. run separate models for each sex:
`jags.M <- run_model(run="test", mix.M, source, discr, ... etc....)`
`jags.F <- run_model(run="test", mix.F, source, discr, ... etc....)`

For a continuous covariate, MixSIAR does a linear regression on the ILR-transformed proportions. Then you can see if the ILR slopes are different by sex, as MixSIAR outputs the posterior for each ILR slope.  Or you could compare the transformed proportion curves instead - this may be clearer since there is one for each source (there are only n.sources - 1 ILR slopes).

Get the ILR slopes for M and F:
`ILR.M <- jags.M$BUGSoutput$sims.list$ilr.cont1`
`ILR.F <- jags.F$BUGSoutput$sims.list$ilr.cont1`

Compare 1st ILR slope M vs. F:
`hist(ILR.M[,1])`
`hist(ILR.F[,1])`

**Comment by MARM09** [comment]
Dear Brian,

Thank you very much for your suggestion. I'll try it and reply back.

Best regards.

Miguel Ángel

**Comment by brianstock** [comment]
Hi Miguel,

Looked into this more... to test if the "Cont effect" model or the "Cont effect + Fixed effect" model is better, you can fit both (i.e. `jags.1` and `jags.2`) and compare the DIC values.  Note: MixSIAR does not fit a different slope term for each FE level, just a different intercept term.

I've also improved the continuous effect plotting function. Now if you run a model with both a continuous and fixed effects, MixSIAR will plot the continuous effect for all levels of the fixed effect.  

To get the new code, install the current Github version (not CRAN).
```
library(devtools)
install_github("brianstock/MixSIAR")
```

After loading MixSIAR, you should see that it's the `3.1.7.9000` development version:
```
library(MixSIAR)
sessionInfo()
```
